/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_TELEMETRY_VEHICLE_DATA_VEHICLE_MIN_PB_H_INCLUDED
#define PB_TELEMETRY_VEHICLE_DATA_VEHICLE_MIN_PB_H_INCLUDED
#include "pb.h"

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
typedef enum _telemetry_vehicle_data_Field {
    telemetry_vehicle_data_Field_Unknown = 0,
    telemetry_vehicle_data_Field_DriveRail = 1,
    telemetry_vehicle_data_Field_ChargeState = 2,
    telemetry_vehicle_data_Field_BmsFullchargecomplete = 3,
    telemetry_vehicle_data_Field_VehicleSpeed = 4,
    telemetry_vehicle_data_Field_Odometer = 5,
    telemetry_vehicle_data_Field_PackVoltage = 6,
    telemetry_vehicle_data_Field_PackCurrent = 7,
    telemetry_vehicle_data_Field_Soc = 8,
    telemetry_vehicle_data_Field_DCDCEnable = 9,
    telemetry_vehicle_data_Field_Gear = 10,
    telemetry_vehicle_data_Field_IsolationResistance = 11,
    telemetry_vehicle_data_Field_PedalPosition = 12,
    telemetry_vehicle_data_Field_BrakePedal = 13,
    telemetry_vehicle_data_Field_DiStateR = 14,
    telemetry_vehicle_data_Field_DiHeatsinkTR = 15,
    telemetry_vehicle_data_Field_DiAxleSpeedR = 16,
    telemetry_vehicle_data_Field_DiTorquemotor = 17,
    telemetry_vehicle_data_Field_DiStatorTempR = 18,
    telemetry_vehicle_data_Field_DiVBatR = 19,
    telemetry_vehicle_data_Field_DiMotorCurrentR = 20,
    telemetry_vehicle_data_Field_Location = 21,
    telemetry_vehicle_data_Field_GpsState = 22,
    telemetry_vehicle_data_Field_GpsHeading = 23,
    telemetry_vehicle_data_Field_NumBrickVoltageMax = 24,
    telemetry_vehicle_data_Field_BrickVoltageMax = 25,
    telemetry_vehicle_data_Field_NumBrickVoltageMin = 26,
    telemetry_vehicle_data_Field_BrickVoltageMin = 27,
    telemetry_vehicle_data_Field_NumModuleTempMax = 28,
    telemetry_vehicle_data_Field_ModuleTempMax = 29,
    telemetry_vehicle_data_Field_NumModuleTempMin = 30,
    telemetry_vehicle_data_Field_ModuleTempMin = 31,
    telemetry_vehicle_data_Field_RatedRange = 32,
    telemetry_vehicle_data_Field_Hvil = 33,
    telemetry_vehicle_data_Field_DCChargingEnergyIn = 34,
    telemetry_vehicle_data_Field_DCChargingPower = 35,
    telemetry_vehicle_data_Field_ACChargingEnergyIn = 36,
    telemetry_vehicle_data_Field_ACChargingPower = 37,
    telemetry_vehicle_data_Field_ChargeLimitSoc = 38,
    telemetry_vehicle_data_Field_FastChargerPresent = 39,
    telemetry_vehicle_data_Field_EstBatteryRange = 40,
    telemetry_vehicle_data_Field_IdealBatteryRange = 41,
    telemetry_vehicle_data_Field_BatteryLevel = 42,
    telemetry_vehicle_data_Field_TimeToFullCharge = 43,
    telemetry_vehicle_data_Field_ScheduledChargingStartTime = 44,
    telemetry_vehicle_data_Field_ScheduledChargingPending = 45,
    telemetry_vehicle_data_Field_ScheduledDepartureTime = 46,
    telemetry_vehicle_data_Field_PreconditioningEnabled = 47,
    telemetry_vehicle_data_Field_ScheduledChargingMode = 48,
    telemetry_vehicle_data_Field_ChargeAmps = 49,
    telemetry_vehicle_data_Field_ChargeEnableRequest = 50,
    telemetry_vehicle_data_Field_ChargerPhases = 51,
    telemetry_vehicle_data_Field_ChargePortColdWeatherMode = 52,
    telemetry_vehicle_data_Field_ChargeCurrentRequest = 53,
    telemetry_vehicle_data_Field_ChargeCurrentRequestMax = 54,
    telemetry_vehicle_data_Field_BatteryHeaterOn = 55,
    telemetry_vehicle_data_Field_NotEnoughPowerToHeat = 56,
    telemetry_vehicle_data_Field_SuperchargerSessionTripPlanner = 57,
    telemetry_vehicle_data_Field_DoorState = 58,
    telemetry_vehicle_data_Field_Locked = 59,
    telemetry_vehicle_data_Field_FdWindow = 60,
    telemetry_vehicle_data_Field_FpWindow = 61,
    telemetry_vehicle_data_Field_RdWindow = 62,
    telemetry_vehicle_data_Field_RpWindow = 63,
    telemetry_vehicle_data_Field_VehicleName = 64,
    telemetry_vehicle_data_Field_SentryMode = 65,
    telemetry_vehicle_data_Field_SpeedLimitMode = 66,
    telemetry_vehicle_data_Field_CurrentLimitMph = 67,
    telemetry_vehicle_data_Field_Version = 68,
    telemetry_vehicle_data_Field_TpmsPressureFl = 69,
    telemetry_vehicle_data_Field_TpmsPressureFr = 70,
    telemetry_vehicle_data_Field_TpmsPressureRl = 71,
    telemetry_vehicle_data_Field_TpmsPressureRr = 72,
    telemetry_vehicle_data_Field_SemitruckTpmsPressureRe1L0 = 73, /* Semi-truck only */
    telemetry_vehicle_data_Field_SemitruckTpmsPressureRe1L1 = 74, /* Semi-truck only */
    telemetry_vehicle_data_Field_SemitruckTpmsPressureRe1R0 = 75, /* Semi-truck only */
    telemetry_vehicle_data_Field_SemitruckTpmsPressureRe1R1 = 76, /* Semi-truck only */
    telemetry_vehicle_data_Field_SemitruckTpmsPressureRe2L0 = 77, /* Semi-truck only */
    telemetry_vehicle_data_Field_SemitruckTpmsPressureRe2L1 = 78, /* Semi-truck only */
    telemetry_vehicle_data_Field_SemitruckTpmsPressureRe2R0 = 79, /* Semi-truck only */
    telemetry_vehicle_data_Field_SemitruckTpmsPressureRe2R1 = 80, /* Semi-truck only */
    telemetry_vehicle_data_Field_TpmsLastSeenPressureTimeFl = 81,
    telemetry_vehicle_data_Field_TpmsLastSeenPressureTimeFr = 82,
    telemetry_vehicle_data_Field_TpmsLastSeenPressureTimeRl = 83,
    telemetry_vehicle_data_Field_TpmsLastSeenPressureTimeRr = 84,
    telemetry_vehicle_data_Field_InsideTemp = 85,
    telemetry_vehicle_data_Field_OutsideTemp = 86,
    telemetry_vehicle_data_Field_SeatHeaterLeft = 87,
    telemetry_vehicle_data_Field_SeatHeaterRight = 88,
    telemetry_vehicle_data_Field_SeatHeaterRearLeft = 89,
    telemetry_vehicle_data_Field_SeatHeaterRearRight = 90,
    telemetry_vehicle_data_Field_SeatHeaterRearCenter = 91,
    telemetry_vehicle_data_Field_AutoSeatClimateLeft = 92,
    telemetry_vehicle_data_Field_AutoSeatClimateRight = 93,
    telemetry_vehicle_data_Field_DriverSeatBelt = 94,
    telemetry_vehicle_data_Field_PassengerSeatBelt = 95,
    telemetry_vehicle_data_Field_DriverSeatOccupied = 96,
    telemetry_vehicle_data_Field_SemitruckPassengerSeatFoldPosition = 97, /* Semi-truck only */
    telemetry_vehicle_data_Field_LateralAcceleration = 98,
    telemetry_vehicle_data_Field_LongitudinalAcceleration = 99,
    telemetry_vehicle_data_Field_Deprecated_2 = 100,
    telemetry_vehicle_data_Field_CruiseSetSpeed = 101,
    telemetry_vehicle_data_Field_LifetimeEnergyUsed = 102,
    telemetry_vehicle_data_Field_LifetimeEnergyUsedDrive = 103, /* Semi-truck only */
    telemetry_vehicle_data_Field_SemitruckTractorParkBrakeStatus = 104, /* Semi-truck only */
    telemetry_vehicle_data_Field_SemitruckTrailerParkBrakeStatus = 105, /* Semi-truck only */
    telemetry_vehicle_data_Field_BrakePedalPos = 106,
    telemetry_vehicle_data_Field_RouteLastUpdated = 107, /* Requires firmware version 2024.26 or later */
    telemetry_vehicle_data_Field_RouteLine = 108, /* Requires firmware version 2024.26 or later */
    telemetry_vehicle_data_Field_MilesToArrival = 109, /* Requires firmware version 2024.26 or later */
    telemetry_vehicle_data_Field_MinutesToArrival = 110, /* Requires firmware version 2024.26 or later */
    telemetry_vehicle_data_Field_OriginLocation = 111, /* Requires firmware version 2024.26 or later */
    telemetry_vehicle_data_Field_DestinationLocation = 112, /* Requires firmware version 2024.26 or later */
    telemetry_vehicle_data_Field_CarType = 113,
    telemetry_vehicle_data_Field_Trim = 114,
    telemetry_vehicle_data_Field_ExteriorColor = 115,
    telemetry_vehicle_data_Field_RoofColor = 116,
    telemetry_vehicle_data_Field_ChargePort = 117,
    telemetry_vehicle_data_Field_ChargePortLatch = 118,
    telemetry_vehicle_data_Field_Experimental_1 = 119,
    telemetry_vehicle_data_Field_Experimental_2 = 120,
    telemetry_vehicle_data_Field_Experimental_3 = 121,
    telemetry_vehicle_data_Field_Experimental_4 = 122,
    telemetry_vehicle_data_Field_GuestModeEnabled = 123,
    telemetry_vehicle_data_Field_PinToDriveEnabled = 124,
    telemetry_vehicle_data_Field_PairedPhoneKeyAndKeyFobQty = 125,
    telemetry_vehicle_data_Field_CruiseFollowDistance = 126,
    telemetry_vehicle_data_Field_AutomaticBlindSpotCamera = 127,
    telemetry_vehicle_data_Field_BlindSpotCollisionWarningChime = 128,
    telemetry_vehicle_data_Field_SpeedLimitWarning = 129,
    telemetry_vehicle_data_Field_ForwardCollisionWarning = 130,
    telemetry_vehicle_data_Field_LaneDepartureAvoidance = 131,
    telemetry_vehicle_data_Field_EmergencyLaneDepartureAvoidance = 132,
    telemetry_vehicle_data_Field_AutomaticEmergencyBrakingOff = 133,
    telemetry_vehicle_data_Field_LifetimeEnergyGainedRegen = 134,
    telemetry_vehicle_data_Field_DiStateF = 135,
    telemetry_vehicle_data_Field_DiStateREL = 136,
    telemetry_vehicle_data_Field_DiStateRER = 137,
    telemetry_vehicle_data_Field_DiHeatsinkTF = 138,
    telemetry_vehicle_data_Field_DiHeatsinkTREL = 139,
    telemetry_vehicle_data_Field_DiHeatsinkTRER = 140,
    telemetry_vehicle_data_Field_DiAxleSpeedF = 141,
    telemetry_vehicle_data_Field_DiAxleSpeedREL = 142,
    telemetry_vehicle_data_Field_DiAxleSpeedRER = 143,
    telemetry_vehicle_data_Field_DiSlaveTorqueCmd = 144,
    telemetry_vehicle_data_Field_DiTorqueActualR = 145,
    telemetry_vehicle_data_Field_DiTorqueActualF = 146,
    telemetry_vehicle_data_Field_DiTorqueActualREL = 147,
    telemetry_vehicle_data_Field_DiTorqueActualRER = 148,
    telemetry_vehicle_data_Field_DiStatorTempF = 149,
    telemetry_vehicle_data_Field_DiStatorTempREL = 150,
    telemetry_vehicle_data_Field_DiStatorTempRER = 151,
    telemetry_vehicle_data_Field_DiVBatF = 152,
    telemetry_vehicle_data_Field_DiVBatREL = 153,
    telemetry_vehicle_data_Field_DiVBatRER = 154,
    telemetry_vehicle_data_Field_DiMotorCurrentF = 155,
    telemetry_vehicle_data_Field_DiMotorCurrentREL = 156,
    telemetry_vehicle_data_Field_DiMotorCurrentRER = 157,
    telemetry_vehicle_data_Field_EnergyRemaining = 158,
    telemetry_vehicle_data_Field_ServiceMode = 159,
    telemetry_vehicle_data_Field_BMSState = 160,
    telemetry_vehicle_data_Field_GuestModeMobileAccessState = 161,
    telemetry_vehicle_data_Field_Deprecated_1 = 162,
    telemetry_vehicle_data_Field_DestinationName = 163, /* Requires firmware version 2024.26 or later */
    telemetry_vehicle_data_Field_DiInverterTR = 164,
    telemetry_vehicle_data_Field_DiInverterTF = 165,
    telemetry_vehicle_data_Field_DiInverterTREL = 166,
    telemetry_vehicle_data_Field_DiInverterTRER = 167,
    telemetry_vehicle_data_Field_Experimental_5 = 168,
    telemetry_vehicle_data_Field_Experimental_6 = 169,
    telemetry_vehicle_data_Field_Experimental_7 = 170,
    telemetry_vehicle_data_Field_Experimental_8 = 171,
    telemetry_vehicle_data_Field_Experimental_9 = 172,
    telemetry_vehicle_data_Field_Experimental_10 = 173,
    telemetry_vehicle_data_Field_Experimental_11 = 174,
    telemetry_vehicle_data_Field_Experimental_12 = 175,
    telemetry_vehicle_data_Field_Experimental_13 = 176,
    telemetry_vehicle_data_Field_Experimental_14 = 177,
    telemetry_vehicle_data_Field_Experimental_15 = 178,
    telemetry_vehicle_data_Field_DetailedChargeState = 179,
    telemetry_vehicle_data_Field_CabinOverheatProtectionMode = 180,
    telemetry_vehicle_data_Field_CabinOverheatProtectionTemperatureLimit = 181,
    telemetry_vehicle_data_Field_CenterDisplay = 182,
    telemetry_vehicle_data_Field_ChargePortDoorOpen = 183,
    telemetry_vehicle_data_Field_ChargerVoltage = 184,
    telemetry_vehicle_data_Field_ChargingCableType = 185,
    telemetry_vehicle_data_Field_ClimateKeeperMode = 186,
    telemetry_vehicle_data_Field_DefrostForPreconditioning = 187,
    telemetry_vehicle_data_Field_DefrostMode = 188,
    telemetry_vehicle_data_Field_EfficiencyPackage = 189,
    telemetry_vehicle_data_Field_EstimatedHoursToChargeTermination = 190,
    telemetry_vehicle_data_Field_EuropeVehicle = 191,
    telemetry_vehicle_data_Field_ExpectedEnergyPercentAtTripArrival = 192,
    telemetry_vehicle_data_Field_FastChargerType = 193,
    telemetry_vehicle_data_Field_HomelinkDeviceCount = 194,
    telemetry_vehicle_data_Field_HomelinkNearby = 195,
    telemetry_vehicle_data_Field_HvacACEnabled = 196,
    telemetry_vehicle_data_Field_HvacAutoMode = 197,
    telemetry_vehicle_data_Field_HvacFanSpeed = 198,
    telemetry_vehicle_data_Field_HvacFanStatus = 199,
    telemetry_vehicle_data_Field_HvacLeftTemperatureRequest = 200,
    telemetry_vehicle_data_Field_HvacPower = 201,
    telemetry_vehicle_data_Field_HvacRightTemperatureRequest = 202,
    telemetry_vehicle_data_Field_HvacSteeringWheelHeatAuto = 203,
    telemetry_vehicle_data_Field_HvacSteeringWheelHeatLevel = 204,
    telemetry_vehicle_data_Field_OffroadLightbarPresent = 205,
    telemetry_vehicle_data_Field_PowershareHoursLeft = 206,
    telemetry_vehicle_data_Field_PowershareInstantaneousPowerKW = 207,
    telemetry_vehicle_data_Field_PowershareStatus = 208,
    telemetry_vehicle_data_Field_PowershareStopReason = 209,
    telemetry_vehicle_data_Field_PowershareType = 210,
    telemetry_vehicle_data_Field_RearDisplayHvacEnabled = 211,
    telemetry_vehicle_data_Field_RearSeatHeaters = 212,
    telemetry_vehicle_data_Field_RemoteStartEnabled = 213,
    telemetry_vehicle_data_Field_RightHandDrive = 214,
    telemetry_vehicle_data_Field_RouteTrafficMinutesDelay = 215,
    telemetry_vehicle_data_Field_SoftwareUpdateDownloadPercentComplete = 216,
    telemetry_vehicle_data_Field_SoftwareUpdateExpectedDurationMinutes = 217,
    telemetry_vehicle_data_Field_SoftwareUpdateInstallationPercentComplete = 218,
    telemetry_vehicle_data_Field_SoftwareUpdateScheduledStartTime = 219,
    telemetry_vehicle_data_Field_SoftwareUpdateVersion = 220,
    telemetry_vehicle_data_Field_TonneauOpenPercent = 221,
    telemetry_vehicle_data_Field_TonneauPosition = 222,
    telemetry_vehicle_data_Field_TonneauTentMode = 223,
    telemetry_vehicle_data_Field_TpmsHardWarnings = 224,
    telemetry_vehicle_data_Field_TpmsSoftWarnings = 225,
    telemetry_vehicle_data_Field_ValetModeEnabled = 226,
    telemetry_vehicle_data_Field_WheelType = 227,
    telemetry_vehicle_data_Field_WiperHeatEnabled = 228,
    telemetry_vehicle_data_Field_LocatedAtHome = 229,
    telemetry_vehicle_data_Field_LocatedAtWork = 230,
    telemetry_vehicle_data_Field_LocatedAtFavorite = 231,
    telemetry_vehicle_data_Field_SettingDistanceUnit = 232,
    telemetry_vehicle_data_Field_SettingTemperatureUnit = 233,
    telemetry_vehicle_data_Field_Setting24HourTime = 234,
    telemetry_vehicle_data_Field_SettingTirePressureUnit = 235,
    telemetry_vehicle_data_Field_SettingChargeUnit = 236,
    telemetry_vehicle_data_Field_ClimateSeatCoolingFrontLeft = 237,
    telemetry_vehicle_data_Field_ClimateSeatCoolingFrontRight = 238,
    telemetry_vehicle_data_Field_LightsHazardsActive = 239,
    telemetry_vehicle_data_Field_LightsTurnSignal = 240,
    telemetry_vehicle_data_Field_LightsHighBeams = 241,
    telemetry_vehicle_data_Field_MediaPlaybackStatus = 242,
    telemetry_vehicle_data_Field_MediaPlaybackSource = 243,
    telemetry_vehicle_data_Field_MediaAudioVolume = 244,
    telemetry_vehicle_data_Field_MediaNowPlayingDuration = 245,
    telemetry_vehicle_data_Field_MediaNowPlayingElapsed = 246,
    telemetry_vehicle_data_Field_MediaNowPlayingArtist = 247,
    telemetry_vehicle_data_Field_MediaNowPlayingTitle = 248,
    telemetry_vehicle_data_Field_MediaNowPlayingAlbum = 249,
    telemetry_vehicle_data_Field_MediaNowPlayingStation = 250,
    telemetry_vehicle_data_Field_MediaAudioVolumeIncrement = 251,
    telemetry_vehicle_data_Field_MediaAudioVolumeMax = 252,
    telemetry_vehicle_data_Field_SunroofInstalled = 253,
    telemetry_vehicle_data_Field_SeatVentEnabled = 254,
    telemetry_vehicle_data_Field_RearDefrostEnabled = 255,
    telemetry_vehicle_data_Field_ChargeRateMilePerHour = 256,
    telemetry_vehicle_data_Field_Deprecated_3 = 257,
    telemetry_vehicle_data_Field_MilesSinceReset = 258,
    telemetry_vehicle_data_Field_SelfDrivingMilesSinceReset = 259
} telemetry_vehicle_data_Field;

/* ChargingState is deprecated and not used */
typedef enum _telemetry_vehicle_data_ChargingState {
    telemetry_vehicle_data_ChargingState_ChargeStateUnknown = 0,
    telemetry_vehicle_data_ChargingState_ChargeStateDisconnected = 1,
    telemetry_vehicle_data_ChargingState_ChargeStateNoPower = 2,
    telemetry_vehicle_data_ChargingState_ChargeStateStarting = 3,
    telemetry_vehicle_data_ChargingState_ChargeStateCharging = 4,
    telemetry_vehicle_data_ChargingState_ChargeStateComplete = 5,
    telemetry_vehicle_data_ChargingState_ChargeStateStopped = 6
} telemetry_vehicle_data_ChargingState;

typedef enum _telemetry_vehicle_data_DetailedChargeStateValue {
    telemetry_vehicle_data_DetailedChargeStateValue_DetailedChargeStateUnknown = 0,
    telemetry_vehicle_data_DetailedChargeStateValue_DetailedChargeStateDisconnected = 1,
    telemetry_vehicle_data_DetailedChargeStateValue_DetailedChargeStateNoPower = 2,
    telemetry_vehicle_data_DetailedChargeStateValue_DetailedChargeStateStarting = 3,
    telemetry_vehicle_data_DetailedChargeStateValue_DetailedChargeStateCharging = 4,
    telemetry_vehicle_data_DetailedChargeStateValue_DetailedChargeStateComplete = 5,
    telemetry_vehicle_data_DetailedChargeStateValue_DetailedChargeStateStopped = 6
} telemetry_vehicle_data_DetailedChargeStateValue;

/* ShiftState are the gear options */
typedef enum _telemetry_vehicle_data_ShiftState {
    telemetry_vehicle_data_ShiftState_ShiftStateUnknown = 0,
    telemetry_vehicle_data_ShiftState_ShiftStateInvalid = 1,
    telemetry_vehicle_data_ShiftState_ShiftStateP = 2,
    telemetry_vehicle_data_ShiftState_ShiftStateR = 3,
    telemetry_vehicle_data_ShiftState_ShiftStateN = 4,
    telemetry_vehicle_data_ShiftState_ShiftStateD = 5,
    telemetry_vehicle_data_ShiftState_ShiftStateSNA = 6
} telemetry_vehicle_data_ShiftState;

typedef enum _telemetry_vehicle_data_FollowDistance {
    telemetry_vehicle_data_FollowDistance_FollowDistanceUnknown = 0,
    telemetry_vehicle_data_FollowDistance_FollowDistance1 = 1,
    telemetry_vehicle_data_FollowDistance_FollowDistance2 = 2,
    telemetry_vehicle_data_FollowDistance_FollowDistance3 = 3,
    telemetry_vehicle_data_FollowDistance_FollowDistance4 = 4,
    telemetry_vehicle_data_FollowDistance_FollowDistance5 = 5,
    telemetry_vehicle_data_FollowDistance_FollowDistance6 = 6,
    telemetry_vehicle_data_FollowDistance_FollowDistance7 = 7
} telemetry_vehicle_data_FollowDistance;

typedef enum _telemetry_vehicle_data_ForwardCollisionSensitivity {
    telemetry_vehicle_data_ForwardCollisionSensitivity_ForwardCollisionSensitivityUnknown = 0,
    telemetry_vehicle_data_ForwardCollisionSensitivity_ForwardCollisionSensitivityOff = 1,
    telemetry_vehicle_data_ForwardCollisionSensitivity_ForwardCollisionSensitivityLate = 2,
    telemetry_vehicle_data_ForwardCollisionSensitivity_ForwardCollisionSensitivityAverage = 3,
    telemetry_vehicle_data_ForwardCollisionSensitivity_ForwardCollisionSensitivityEarly = 4
} telemetry_vehicle_data_ForwardCollisionSensitivity;

typedef enum _telemetry_vehicle_data_GuestModeMobileAccess {
    telemetry_vehicle_data_GuestModeMobileAccess_GuestModeMobileAccessUnknown = 0,
    telemetry_vehicle_data_GuestModeMobileAccess_GuestModeMobileAccessInit = 1,
    telemetry_vehicle_data_GuestModeMobileAccess_GuestModeMobileAccessNotAuthenticated = 2,
    telemetry_vehicle_data_GuestModeMobileAccess_GuestModeMobileAccessAuthenticated = 3,
    telemetry_vehicle_data_GuestModeMobileAccess_GuestModeMobileAccessAbortedDriving = 4,
    telemetry_vehicle_data_GuestModeMobileAccess_GuestModeMobileAccessAbortedUsingRemoteStart = 5,
    telemetry_vehicle_data_GuestModeMobileAccess_GuestModeMobileAccessAbortedUsingBLEKeys = 6,
    telemetry_vehicle_data_GuestModeMobileAccess_GuestModeMobileAccessAbortedValetMode = 7,
    telemetry_vehicle_data_GuestModeMobileAccess_GuestModeMobileAccessAbortedGuestModeOff = 8,
    telemetry_vehicle_data_GuestModeMobileAccess_GuestModeMobileAccessAbortedDriveAuthTimeExceeded = 9,
    telemetry_vehicle_data_GuestModeMobileAccess_GuestModeMobileAccessAbortedNoDataReceived = 10,
    telemetry_vehicle_data_GuestModeMobileAccess_GuestModeMobileAccessRequestingFromMothership = 11,
    telemetry_vehicle_data_GuestModeMobileAccess_GuestModeMobileAccessRequestingFromAuthD = 12,
    telemetry_vehicle_data_GuestModeMobileAccess_GuestModeMobileAccessAbortedFetchFailed = 13,
    telemetry_vehicle_data_GuestModeMobileAccess_GuestModeMobileAccessAbortedBadDataReceived = 14,
    telemetry_vehicle_data_GuestModeMobileAccess_GuestModeMobileAccessShowingQRCode = 15,
    telemetry_vehicle_data_GuestModeMobileAccess_GuestModeMobileAccessSwipedAway = 16,
    telemetry_vehicle_data_GuestModeMobileAccess_GuestModeMobileAccessDismissedQRCodeExpired = 17,
    telemetry_vehicle_data_GuestModeMobileAccess_GuestModeMobileAccessSucceededPairedNewBLEKey = 18
} telemetry_vehicle_data_GuestModeMobileAccess;

typedef enum _telemetry_vehicle_data_LaneAssistLevel {
    telemetry_vehicle_data_LaneAssistLevel_LaneAssistLevelUnknown = 0,
    telemetry_vehicle_data_LaneAssistLevel_LaneAssistLevelNone = 1,
    telemetry_vehicle_data_LaneAssistLevel_LaneAssistLevelWarning = 2,
    telemetry_vehicle_data_LaneAssistLevel_LaneAssistLevelAssist = 3
} telemetry_vehicle_data_LaneAssistLevel;

typedef enum _telemetry_vehicle_data_ScheduledChargingModeValue {
    telemetry_vehicle_data_ScheduledChargingModeValue_ScheduledChargingModeUnknown = 0,
    telemetry_vehicle_data_ScheduledChargingModeValue_ScheduledChargingModeOff = 1,
    telemetry_vehicle_data_ScheduledChargingModeValue_ScheduledChargingModeStartAt = 2,
    telemetry_vehicle_data_ScheduledChargingModeValue_ScheduledChargingModeDepartBy = 3
} telemetry_vehicle_data_ScheduledChargingModeValue;

typedef enum _telemetry_vehicle_data_SentryModeState {
    telemetry_vehicle_data_SentryModeState_SentryModeStateUnknown = 0,
    telemetry_vehicle_data_SentryModeState_SentryModeStateOff = 1,
    telemetry_vehicle_data_SentryModeState_SentryModeStateIdle = 2,
    telemetry_vehicle_data_SentryModeState_SentryModeStateArmed = 3,
    telemetry_vehicle_data_SentryModeState_SentryModeStateAware = 4,
    telemetry_vehicle_data_SentryModeState_SentryModeStatePanic = 5,
    telemetry_vehicle_data_SentryModeState_SentryModeStateQuiet = 6
} telemetry_vehicle_data_SentryModeState;

typedef enum _telemetry_vehicle_data_SpeedAssistLevel {
    telemetry_vehicle_data_SpeedAssistLevel_SpeedAssistLevelUnknown = 0,
    telemetry_vehicle_data_SpeedAssistLevel_SpeedAssistLevelNone = 1,
    telemetry_vehicle_data_SpeedAssistLevel_SpeedAssistLevelDisplay = 2,
    telemetry_vehicle_data_SpeedAssistLevel_SpeedAssistLevelChime = 3
} telemetry_vehicle_data_SpeedAssistLevel;

typedef enum _telemetry_vehicle_data_BMSStateValue {
    telemetry_vehicle_data_BMSStateValue_BMSStateUnknown = 0,
    telemetry_vehicle_data_BMSStateValue_BMSStateStandby = 1,
    telemetry_vehicle_data_BMSStateValue_BMSStateDrive = 2,
    telemetry_vehicle_data_BMSStateValue_BMSStateSupport = 3,
    telemetry_vehicle_data_BMSStateValue_BMSStateCharge = 4,
    telemetry_vehicle_data_BMSStateValue_BMSStateFEIM = 5,
    telemetry_vehicle_data_BMSStateValue_BMSStateClearFault = 6,
    telemetry_vehicle_data_BMSStateValue_BMSStateFault = 7,
    telemetry_vehicle_data_BMSStateValue_BMSStateWeld = 8,
    telemetry_vehicle_data_BMSStateValue_BMSStateTest = 9,
    telemetry_vehicle_data_BMSStateValue_BMSStateSNA = 10
} telemetry_vehicle_data_BMSStateValue;

typedef enum _telemetry_vehicle_data_BuckleStatus {
    telemetry_vehicle_data_BuckleStatus_BuckleStatusUnknown = 0,
    telemetry_vehicle_data_BuckleStatus_BuckleStatusUnlatched = 1,
    telemetry_vehicle_data_BuckleStatus_BuckleStatusLatched = 2,
    telemetry_vehicle_data_BuckleStatus_BuckleStatusFaulted = 3
} telemetry_vehicle_data_BuckleStatus;

typedef enum _telemetry_vehicle_data_CarTypeValue {
    telemetry_vehicle_data_CarTypeValue_CarTypeUnknown = 0,
    telemetry_vehicle_data_CarTypeValue_CarTypeModelS = 1,
    telemetry_vehicle_data_CarTypeValue_CarTypeModelX = 2,
    telemetry_vehicle_data_CarTypeValue_CarTypeModel3 = 3,
    telemetry_vehicle_data_CarTypeValue_CarTypeModelY = 4,
    telemetry_vehicle_data_CarTypeValue_CarTypeSemiTruck = 5,
    telemetry_vehicle_data_CarTypeValue_CarTypeCybertruck = 6
} telemetry_vehicle_data_CarTypeValue;

typedef enum _telemetry_vehicle_data_ChargePortValue {
    telemetry_vehicle_data_ChargePortValue_ChargePortUnknown = 0,
    telemetry_vehicle_data_ChargePortValue_ChargePortUS = 1,
    telemetry_vehicle_data_ChargePortValue_ChargePortEU = 2,
    telemetry_vehicle_data_ChargePortValue_ChargePortGB = 3,
    telemetry_vehicle_data_ChargePortValue_ChargePortCCS = 4
} telemetry_vehicle_data_ChargePortValue;

typedef enum _telemetry_vehicle_data_ChargePortLatchValue {
    telemetry_vehicle_data_ChargePortLatchValue_ChargePortLatchUnknown = 0,
    telemetry_vehicle_data_ChargePortLatchValue_ChargePortLatchSNA = 1,
    telemetry_vehicle_data_ChargePortLatchValue_ChargePortLatchDisengaged = 2,
    telemetry_vehicle_data_ChargePortLatchValue_ChargePortLatchEngaged = 3,
    telemetry_vehicle_data_ChargePortLatchValue_ChargePortLatchBlocking = 4
} telemetry_vehicle_data_ChargePortLatchValue;

typedef enum _telemetry_vehicle_data_DriveInverterState {
    telemetry_vehicle_data_DriveInverterState_DriveInverterStateUnknown = 0,
    telemetry_vehicle_data_DriveInverterState_DriveInverterStateUnavailable = 1,
    telemetry_vehicle_data_DriveInverterState_DriveInverterStateStandby = 2,
    telemetry_vehicle_data_DriveInverterState_DriveInverterStateFault = 3,
    telemetry_vehicle_data_DriveInverterState_DriveInverterStateAbort = 4,
    telemetry_vehicle_data_DriveInverterState_DriveInverterStateEnable = 5
} telemetry_vehicle_data_DriveInverterState;

typedef enum _telemetry_vehicle_data_HvilStatus {
    telemetry_vehicle_data_HvilStatus_HvilStatusUnknown = 0,
    telemetry_vehicle_data_HvilStatus_HvilStatusFault = 1,
    telemetry_vehicle_data_HvilStatus_HvilStatusOK = 2
} telemetry_vehicle_data_HvilStatus;

typedef enum _telemetry_vehicle_data_WindowState {
    telemetry_vehicle_data_WindowState_WindowStateUnknown = 0,
    telemetry_vehicle_data_WindowState_WindowStateClosed = 1,
    telemetry_vehicle_data_WindowState_WindowStatePartiallyOpen = 2,
    telemetry_vehicle_data_WindowState_WindowStateOpened = 3
} telemetry_vehicle_data_WindowState;

typedef enum _telemetry_vehicle_data_SeatFoldPosition {
    telemetry_vehicle_data_SeatFoldPosition_SeatFoldPositionUnknown = 0,
    telemetry_vehicle_data_SeatFoldPosition_SeatFoldPositionSNA = 1,
    telemetry_vehicle_data_SeatFoldPosition_SeatFoldPositionFaulted = 2,
    telemetry_vehicle_data_SeatFoldPosition_SeatFoldPositionNotConfigured = 3,
    telemetry_vehicle_data_SeatFoldPosition_SeatFoldPositionFolded = 4,
    telemetry_vehicle_data_SeatFoldPosition_SeatFoldPositionUnfolded = 5
} telemetry_vehicle_data_SeatFoldPosition;

typedef enum _telemetry_vehicle_data_TractorAirStatus {
    telemetry_vehicle_data_TractorAirStatus_TractorAirStatusUnknown = 0,
    telemetry_vehicle_data_TractorAirStatus_TractorAirStatusNotAvailable = 1,
    telemetry_vehicle_data_TractorAirStatus_TractorAirStatusError = 2,
    telemetry_vehicle_data_TractorAirStatus_TractorAirStatusCharged = 3,
    telemetry_vehicle_data_TractorAirStatus_TractorAirStatusBuildingPressureIntermediate = 4,
    telemetry_vehicle_data_TractorAirStatus_TractorAirStatusExhaustingPressureIntermediate = 5,
    telemetry_vehicle_data_TractorAirStatus_TractorAirStatusExhausted = 6
} telemetry_vehicle_data_TractorAirStatus;

typedef enum _telemetry_vehicle_data_TrailerAirStatus {
    telemetry_vehicle_data_TrailerAirStatus_TrailerAirStatusUnknown = 0,
    telemetry_vehicle_data_TrailerAirStatus_TrailerAirStatusSNA = 1,
    telemetry_vehicle_data_TrailerAirStatus_TrailerAirStatusInvalid = 2,
    telemetry_vehicle_data_TrailerAirStatus_TrailerAirStatusBobtailMode = 3,
    telemetry_vehicle_data_TrailerAirStatus_TrailerAirStatusCharged = 4,
    telemetry_vehicle_data_TrailerAirStatus_TrailerAirStatusBuildingPressureIntermediate = 5,
    telemetry_vehicle_data_TrailerAirStatus_TrailerAirStatusExhaustingPressureIntermediate = 6,
    telemetry_vehicle_data_TrailerAirStatus_TrailerAirStatusExhausted = 7
} telemetry_vehicle_data_TrailerAirStatus;

typedef enum _telemetry_vehicle_data_HvacAutoModeState {
    telemetry_vehicle_data_HvacAutoModeState_HvacAutoModeStateUnknown = 0,
    telemetry_vehicle_data_HvacAutoModeState_HvacAutoModeStateOn = 1,
    telemetry_vehicle_data_HvacAutoModeState_HvacAutoModeStateOverride = 2
} telemetry_vehicle_data_HvacAutoModeState;

typedef enum _telemetry_vehicle_data_CabinOverheatProtectionModeState {
    telemetry_vehicle_data_CabinOverheatProtectionModeState_CabinOverheatProtectionModeStateUnknown = 0,
    telemetry_vehicle_data_CabinOverheatProtectionModeState_CabinOverheatProtectionModeStateOff = 1,
    telemetry_vehicle_data_CabinOverheatProtectionModeState_CabinOverheatProtectionModeStateOn = 2,
    telemetry_vehicle_data_CabinOverheatProtectionModeState_CabinOverheatProtectionModeStateFanOnly = 3
} telemetry_vehicle_data_CabinOverheatProtectionModeState;

typedef enum _telemetry_vehicle_data_ClimateOverheatProtectionTempLimit {
    telemetry_vehicle_data_ClimateOverheatProtectionTempLimit_ClimateOverheatProtectionTempLimitUnknown = 0,
    telemetry_vehicle_data_ClimateOverheatProtectionTempLimit_ClimateOverheatProtectionTempLimitHigh = 1,
    telemetry_vehicle_data_ClimateOverheatProtectionTempLimit_ClimateOverheatProtectionTempLimitMedium = 2,
    telemetry_vehicle_data_ClimateOverheatProtectionTempLimit_ClimateOverheatProtectionTempLimitLow = 3
} telemetry_vehicle_data_ClimateOverheatProtectionTempLimit;

typedef enum _telemetry_vehicle_data_DefrostModeState {
    telemetry_vehicle_data_DefrostModeState_DefrostModeStateUnknown = 0,
    telemetry_vehicle_data_DefrostModeState_DefrostModeStateOff = 1,
    telemetry_vehicle_data_DefrostModeState_DefrostModeStateNormal = 2,
    telemetry_vehicle_data_DefrostModeState_DefrostModeStateMax = 3,
    telemetry_vehicle_data_DefrostModeState_DefrostModeStateAutoDefog = 4
} telemetry_vehicle_data_DefrostModeState;

typedef enum _telemetry_vehicle_data_ClimateKeeperModeState {
    telemetry_vehicle_data_ClimateKeeperModeState_ClimateKeeperModeStateUnknown = 0,
    telemetry_vehicle_data_ClimateKeeperModeState_ClimateKeeperModeStateOff = 1,
    telemetry_vehicle_data_ClimateKeeperModeState_ClimateKeeperModeStateOn = 2,
    telemetry_vehicle_data_ClimateKeeperModeState_ClimateKeeperModeStateDog = 3,
    telemetry_vehicle_data_ClimateKeeperModeState_ClimateKeeperModeStateParty = 4
} telemetry_vehicle_data_ClimateKeeperModeState;

typedef enum _telemetry_vehicle_data_HvacPowerState {
    telemetry_vehicle_data_HvacPowerState_HvacPowerStateUnknown = 0,
    telemetry_vehicle_data_HvacPowerState_HvacPowerStateOff = 1,
    telemetry_vehicle_data_HvacPowerState_HvacPowerStateOn = 2,
    telemetry_vehicle_data_HvacPowerState_HvacPowerStatePrecondition = 3,
    telemetry_vehicle_data_HvacPowerState_HvacPowerStateOverheatProtect = 4
} telemetry_vehicle_data_HvacPowerState;

typedef enum _telemetry_vehicle_data_FastCharger {
    telemetry_vehicle_data_FastCharger_FastChargerUnknown = 0,
    telemetry_vehicle_data_FastCharger_FastChargerSupercharger = 1,
    telemetry_vehicle_data_FastCharger_FastChargerCHAdeMO = 2,
    telemetry_vehicle_data_FastCharger_FastChargerGB = 3,
    telemetry_vehicle_data_FastCharger_FastChargerACSingleWireCAN = 4,
    telemetry_vehicle_data_FastCharger_FastChargerCombo = 5,
    telemetry_vehicle_data_FastCharger_FastChargerMCSingleWireCAN = 6,
    telemetry_vehicle_data_FastCharger_FastChargerOther = 7,
    telemetry_vehicle_data_FastCharger_FastChargerSNA = 8
} telemetry_vehicle_data_FastCharger;

typedef enum _telemetry_vehicle_data_CableType {
    telemetry_vehicle_data_CableType_CableTypeUnknown = 0,
    telemetry_vehicle_data_CableType_CableTypeIEC = 1,
    telemetry_vehicle_data_CableType_CableTypeSAE = 2,
    telemetry_vehicle_data_CableType_CableTypeGB_AC = 3,
    telemetry_vehicle_data_CableType_CableTypeGB_DC = 4,
    telemetry_vehicle_data_CableType_CableTypeSNA = 5
} telemetry_vehicle_data_CableType;

typedef enum _telemetry_vehicle_data_TonneauTentModeState {
    telemetry_vehicle_data_TonneauTentModeState_TonneauTentModeStateUnknown = 0,
    telemetry_vehicle_data_TonneauTentModeState_TonneauTentModeStateInactive = 1,
    telemetry_vehicle_data_TonneauTentModeState_TonneauTentModeStateMoving = 2,
    telemetry_vehicle_data_TonneauTentModeState_TonneauTentModeStateFailed = 3,
    telemetry_vehicle_data_TonneauTentModeState_TonneauTentModeStateActive = 4
} telemetry_vehicle_data_TonneauTentModeState;

typedef enum _telemetry_vehicle_data_TonneauPositionState {
    telemetry_vehicle_data_TonneauPositionState_TonneauPositionStateUnknown = 0,
    telemetry_vehicle_data_TonneauPositionState_TonneauPositionStateInvalid = 1,
    telemetry_vehicle_data_TonneauPositionState_TonneauPositionStateClosed = 2,
    telemetry_vehicle_data_TonneauPositionState_TonneauPositionStatePartiallyOpen = 3,
    telemetry_vehicle_data_TonneauPositionState_TonneauPositionStateFullyOpen = 4
} telemetry_vehicle_data_TonneauPositionState;

typedef enum _telemetry_vehicle_data_PowershareState {
    telemetry_vehicle_data_PowershareState_PowershareStateUnknown = 0,
    telemetry_vehicle_data_PowershareState_PowershareStateInactive = 1,
    telemetry_vehicle_data_PowershareState_PowershareStateHandshaking = 2,
    telemetry_vehicle_data_PowershareState_PowershareStateInit = 3,
    telemetry_vehicle_data_PowershareState_PowershareStateEnabled = 4,
    telemetry_vehicle_data_PowershareState_PowershareStateEnabledReconnectingSoon = 5,
    telemetry_vehicle_data_PowershareState_PowershareStateStopped = 6
} telemetry_vehicle_data_PowershareState;

typedef enum _telemetry_vehicle_data_PowershareStopReasonStatus {
    telemetry_vehicle_data_PowershareStopReasonStatus_PowershareStopReasonStatusUnknown = 0,
    telemetry_vehicle_data_PowershareStopReasonStatus_PowershareStopReasonStatusNone = 1,
    telemetry_vehicle_data_PowershareStopReasonStatus_PowershareStopReasonStatusSOCTooLow = 2,
    telemetry_vehicle_data_PowershareStopReasonStatus_PowershareStopReasonStatusRetry = 3,
    telemetry_vehicle_data_PowershareStopReasonStatus_PowershareStopReasonStatusFault = 4,
    telemetry_vehicle_data_PowershareStopReasonStatus_PowershareStopReasonStatusUser = 5,
    telemetry_vehicle_data_PowershareStopReasonStatus_PowershareStopReasonStatusReconnecting = 6,
    telemetry_vehicle_data_PowershareStopReasonStatus_PowershareStopReasonStatusAuthentication = 7
} telemetry_vehicle_data_PowershareStopReasonStatus;

typedef enum _telemetry_vehicle_data_PowershareTypeStatus {
    telemetry_vehicle_data_PowershareTypeStatus_PowershareTypeStatusUnknown = 0,
    telemetry_vehicle_data_PowershareTypeStatus_PowershareTypeStatusNone = 1,
    telemetry_vehicle_data_PowershareTypeStatus_PowershareTypeStatusLoad = 2,
    telemetry_vehicle_data_PowershareTypeStatus_PowershareTypeStatusHome = 3
} telemetry_vehicle_data_PowershareTypeStatus;

typedef enum _telemetry_vehicle_data_DisplayState {
    telemetry_vehicle_data_DisplayState_DisplayStateUnknown = 0,
    telemetry_vehicle_data_DisplayState_DisplayStateOff = 1,
    telemetry_vehicle_data_DisplayState_DisplayStateDim = 2,
    telemetry_vehicle_data_DisplayState_DisplayStateAccessory = 3,
    telemetry_vehicle_data_DisplayState_DisplayStateOn = 4,
    telemetry_vehicle_data_DisplayState_DisplayStateDriving = 5,
    telemetry_vehicle_data_DisplayState_DisplayStateCharging = 6,
    telemetry_vehicle_data_DisplayState_DisplayStateLock = 7,
    telemetry_vehicle_data_DisplayState_DisplayStateSentry = 8,
    telemetry_vehicle_data_DisplayState_DisplayStateDog = 9,
    telemetry_vehicle_data_DisplayState_DisplayStateEntertainment = 10
} telemetry_vehicle_data_DisplayState;

typedef enum _telemetry_vehicle_data_DistanceUnit {
    telemetry_vehicle_data_DistanceUnit_DistanceUnitUnknown = 0,
    telemetry_vehicle_data_DistanceUnit_DistanceUnitMiles = 1,
    telemetry_vehicle_data_DistanceUnit_DistanceUnitKilometers = 2
} telemetry_vehicle_data_DistanceUnit;

typedef enum _telemetry_vehicle_data_TemperatureUnit {
    telemetry_vehicle_data_TemperatureUnit_TemperatureUnitUnknown = 0,
    telemetry_vehicle_data_TemperatureUnit_TemperatureUnitFahrenheit = 1,
    telemetry_vehicle_data_TemperatureUnit_TemperatureUnitCelsius = 2
} telemetry_vehicle_data_TemperatureUnit;

typedef enum _telemetry_vehicle_data_PressureUnit {
    telemetry_vehicle_data_PressureUnit_PressureUnitUnknown = 0,
    telemetry_vehicle_data_PressureUnit_PressureUnitPsi = 1,
    telemetry_vehicle_data_PressureUnit_PressureUnitBar = 2
} telemetry_vehicle_data_PressureUnit;

typedef enum _telemetry_vehicle_data_ChargeUnitPreference {
    telemetry_vehicle_data_ChargeUnitPreference_ChargeUnitUnknown = 0,
    telemetry_vehicle_data_ChargeUnitPreference_ChargeUnitDistance = 1,
    telemetry_vehicle_data_ChargeUnitPreference_ChargeUnitPercent = 2
} telemetry_vehicle_data_ChargeUnitPreference;

typedef enum _telemetry_vehicle_data_SunroofInstalledState {
    telemetry_vehicle_data_SunroofInstalledState_SunroofInstalledStateUnknown = 0,
    telemetry_vehicle_data_SunroofInstalledState_SunroofInstalledStateNotInstalled = 1,
    telemetry_vehicle_data_SunroofInstalledState_SunroofInstalledStateGen1Installed = 2,
    telemetry_vehicle_data_SunroofInstalledState_SunroofInstalledStateGen2Installed = 3
} telemetry_vehicle_data_SunroofInstalledState;

typedef enum _telemetry_vehicle_data_TurnSignalState {
    telemetry_vehicle_data_TurnSignalState_TurnSignalStateUnknown = 0,
    telemetry_vehicle_data_TurnSignalState_TurnSignalStateOff = 1,
    telemetry_vehicle_data_TurnSignalState_TurnSignalStateLeft = 2,
    telemetry_vehicle_data_TurnSignalState_TurnSignalStateRight = 3,
    telemetry_vehicle_data_TurnSignalState_TurnSignalStateBoth = 4
} telemetry_vehicle_data_TurnSignalState;

typedef enum _telemetry_vehicle_data_MediaStatus {
    telemetry_vehicle_data_MediaStatus_MediaStatusUnknown = 0,
    telemetry_vehicle_data_MediaStatus_MediaStatusStopped = 1,
    telemetry_vehicle_data_MediaStatus_MediaStatusPlaying = 2,
    telemetry_vehicle_data_MediaStatus_MediaStatusPaused = 3
} telemetry_vehicle_data_MediaStatus;

/* Struct definitions */
/* LocationValue is a Datum value type */
typedef struct _telemetry_vehicle_data_LocationValue {
    double latitude;
    double longitude;
} telemetry_vehicle_data_LocationValue;

typedef struct _telemetry_vehicle_data_Doors {
    bool DriverFront;
    bool DriverRear;
    bool PassengerFront;
    bool PassengerRear;
    bool TrunkFront;
    bool TrunkRear;
} telemetry_vehicle_data_Doors;

typedef struct _telemetry_vehicle_data_TireLocation {
    bool front_left;
    bool front_right;
    bool rear_left;
    bool rear_right;
    bool semi_middle_axle_left_2;
    bool semi_middle_axle_right_2;
    bool semi_rear_axle_left;
    bool semi_rear_axle_right;
    bool semi_rear_axle_left_2;
    bool semi_rear_axle_right_2;
} telemetry_vehicle_data_TireLocation;

typedef struct _telemetry_vehicle_data_Time {
    int32_t hour;
    int32_t minute;
    int32_t second;
} telemetry_vehicle_data_Time;

/* Value is a dynamic Datum type.  Most Datums are strings and is the default format
 Note: Fields may have their types updated with different software and vehicle
 versions to optimize for precision or space */
typedef struct _telemetry_vehicle_data_Value {
    pb_size_t which_value;
    union {
        pb_callback_t string_value;
        int32_t int_value;
        int64_t long_value;
        float float_value;
        double double_value;
        bool boolean_value;
        telemetry_vehicle_data_LocationValue location_value;
        telemetry_vehicle_data_ChargingState charging_value;
        telemetry_vehicle_data_ShiftState shift_state_value;
        bool invalid;
        telemetry_vehicle_data_LaneAssistLevel lane_assist_level_value;
        telemetry_vehicle_data_ScheduledChargingModeValue scheduled_charging_mode_value;
        telemetry_vehicle_data_SentryModeState sentry_mode_state_value;
        telemetry_vehicle_data_SpeedAssistLevel speed_assist_level_value;
        telemetry_vehicle_data_BMSStateValue bms_state_value;
        telemetry_vehicle_data_BuckleStatus buckle_status_value;
        telemetry_vehicle_data_CarTypeValue car_type_value;
        telemetry_vehicle_data_ChargePortValue charge_port_value;
        telemetry_vehicle_data_ChargePortLatchValue charge_port_latch_value;
        telemetry_vehicle_data_Doors door_value;
        telemetry_vehicle_data_DriveInverterState drive_inverter_state_value;
        telemetry_vehicle_data_HvilStatus hvil_status_value;
        telemetry_vehicle_data_WindowState window_state_value;
        telemetry_vehicle_data_SeatFoldPosition seat_fold_position_value;
        telemetry_vehicle_data_TractorAirStatus tractor_air_status_value;
        telemetry_vehicle_data_FollowDistance follow_distance_value;
        telemetry_vehicle_data_ForwardCollisionSensitivity forward_collision_sensitivity_value;
        telemetry_vehicle_data_GuestModeMobileAccess guest_mode_mobile_access_value;
        telemetry_vehicle_data_TrailerAirStatus trailer_air_status_value;
        telemetry_vehicle_data_Time time_value;
        telemetry_vehicle_data_DetailedChargeStateValue detailed_charge_state_value;
        telemetry_vehicle_data_HvacAutoModeState hvac_auto_mode_value;
        telemetry_vehicle_data_CabinOverheatProtectionModeState cabin_overheat_protection_mode_value;
        telemetry_vehicle_data_ClimateOverheatProtectionTempLimit cabin_overheat_protection_temperature_limit_value;
        telemetry_vehicle_data_DefrostModeState defrost_mode_value;
        telemetry_vehicle_data_ClimateKeeperModeState climate_keeper_mode_value;
        telemetry_vehicle_data_HvacPowerState hvac_power_value;
        telemetry_vehicle_data_TireLocation tire_location_value;
        telemetry_vehicle_data_FastCharger fast_charger_value;
        telemetry_vehicle_data_CableType cable_type_value;
        telemetry_vehicle_data_TonneauTentModeState tonneau_tent_mode_value;
        telemetry_vehicle_data_TonneauPositionState tonneau_position_value;
        telemetry_vehicle_data_PowershareTypeStatus powershare_type_value;
        telemetry_vehicle_data_PowershareState powershare_state_value;
        telemetry_vehicle_data_PowershareStopReasonStatus powershare_stop_reason_value;
        telemetry_vehicle_data_DisplayState display_state_value;
        telemetry_vehicle_data_DistanceUnit distance_unit_value;
        telemetry_vehicle_data_TemperatureUnit temperature_unit_value;
        telemetry_vehicle_data_PressureUnit pressure_unit_value;
        telemetry_vehicle_data_ChargeUnitPreference charge_unit_preference_value;
        telemetry_vehicle_data_TurnSignalState turn_signal_state_value;
        telemetry_vehicle_data_MediaStatus media_status_value;
        telemetry_vehicle_data_SunroofInstalledState sunroof_installed_state_value;
    } value;
} telemetry_vehicle_data_Value;

/* Datum represents a single field and its value */
typedef struct _telemetry_vehicle_data_Datum {
    telemetry_vehicle_data_Field key;
    bool has_value;
    telemetry_vehicle_data_Value value;
} telemetry_vehicle_data_Datum;

/* Payload holds a collection of values, and may not have a vin */
typedef struct _telemetry_vehicle_data_Payload {
    pb_callback_t data;
    pb_callback_t vin;
    bool is_resend;
} telemetry_vehicle_data_Payload;


#ifdef __cplusplus
extern "C" {
#endif

/* Helper constants for enums */
#define _telemetry_vehicle_data_Field_MIN telemetry_vehicle_data_Field_Unknown
#define _telemetry_vehicle_data_Field_MAX telemetry_vehicle_data_Field_SelfDrivingMilesSinceReset
#define _telemetry_vehicle_data_Field_ARRAYSIZE ((telemetry_vehicle_data_Field)(telemetry_vehicle_data_Field_SelfDrivingMilesSinceReset+1))

#define _telemetry_vehicle_data_ChargingState_MIN telemetry_vehicle_data_ChargingState_ChargeStateUnknown
#define _telemetry_vehicle_data_ChargingState_MAX telemetry_vehicle_data_ChargingState_ChargeStateStopped
#define _telemetry_vehicle_data_ChargingState_ARRAYSIZE ((telemetry_vehicle_data_ChargingState)(telemetry_vehicle_data_ChargingState_ChargeStateStopped+1))

#define _telemetry_vehicle_data_DetailedChargeStateValue_MIN telemetry_vehicle_data_DetailedChargeStateValue_DetailedChargeStateUnknown
#define _telemetry_vehicle_data_DetailedChargeStateValue_MAX telemetry_vehicle_data_DetailedChargeStateValue_DetailedChargeStateStopped
#define _telemetry_vehicle_data_DetailedChargeStateValue_ARRAYSIZE ((telemetry_vehicle_data_DetailedChargeStateValue)(telemetry_vehicle_data_DetailedChargeStateValue_DetailedChargeStateStopped+1))

#define _telemetry_vehicle_data_ShiftState_MIN telemetry_vehicle_data_ShiftState_ShiftStateUnknown
#define _telemetry_vehicle_data_ShiftState_MAX telemetry_vehicle_data_ShiftState_ShiftStateSNA
#define _telemetry_vehicle_data_ShiftState_ARRAYSIZE ((telemetry_vehicle_data_ShiftState)(telemetry_vehicle_data_ShiftState_ShiftStateSNA+1))

#define _telemetry_vehicle_data_FollowDistance_MIN telemetry_vehicle_data_FollowDistance_FollowDistanceUnknown
#define _telemetry_vehicle_data_FollowDistance_MAX telemetry_vehicle_data_FollowDistance_FollowDistance7
#define _telemetry_vehicle_data_FollowDistance_ARRAYSIZE ((telemetry_vehicle_data_FollowDistance)(telemetry_vehicle_data_FollowDistance_FollowDistance7+1))

#define _telemetry_vehicle_data_ForwardCollisionSensitivity_MIN telemetry_vehicle_data_ForwardCollisionSensitivity_ForwardCollisionSensitivityUnknown
#define _telemetry_vehicle_data_ForwardCollisionSensitivity_MAX telemetry_vehicle_data_ForwardCollisionSensitivity_ForwardCollisionSensitivityEarly
#define _telemetry_vehicle_data_ForwardCollisionSensitivity_ARRAYSIZE ((telemetry_vehicle_data_ForwardCollisionSensitivity)(telemetry_vehicle_data_ForwardCollisionSensitivity_ForwardCollisionSensitivityEarly+1))

#define _telemetry_vehicle_data_GuestModeMobileAccess_MIN telemetry_vehicle_data_GuestModeMobileAccess_GuestModeMobileAccessUnknown
#define _telemetry_vehicle_data_GuestModeMobileAccess_MAX telemetry_vehicle_data_GuestModeMobileAccess_GuestModeMobileAccessSucceededPairedNewBLEKey
#define _telemetry_vehicle_data_GuestModeMobileAccess_ARRAYSIZE ((telemetry_vehicle_data_GuestModeMobileAccess)(telemetry_vehicle_data_GuestModeMobileAccess_GuestModeMobileAccessSucceededPairedNewBLEKey+1))

#define _telemetry_vehicle_data_LaneAssistLevel_MIN telemetry_vehicle_data_LaneAssistLevel_LaneAssistLevelUnknown
#define _telemetry_vehicle_data_LaneAssistLevel_MAX telemetry_vehicle_data_LaneAssistLevel_LaneAssistLevelAssist
#define _telemetry_vehicle_data_LaneAssistLevel_ARRAYSIZE ((telemetry_vehicle_data_LaneAssistLevel)(telemetry_vehicle_data_LaneAssistLevel_LaneAssistLevelAssist+1))

#define _telemetry_vehicle_data_ScheduledChargingModeValue_MIN telemetry_vehicle_data_ScheduledChargingModeValue_ScheduledChargingModeUnknown
#define _telemetry_vehicle_data_ScheduledChargingModeValue_MAX telemetry_vehicle_data_ScheduledChargingModeValue_ScheduledChargingModeDepartBy
#define _telemetry_vehicle_data_ScheduledChargingModeValue_ARRAYSIZE ((telemetry_vehicle_data_ScheduledChargingModeValue)(telemetry_vehicle_data_ScheduledChargingModeValue_ScheduledChargingModeDepartBy+1))

#define _telemetry_vehicle_data_SentryModeState_MIN telemetry_vehicle_data_SentryModeState_SentryModeStateUnknown
#define _telemetry_vehicle_data_SentryModeState_MAX telemetry_vehicle_data_SentryModeState_SentryModeStateQuiet
#define _telemetry_vehicle_data_SentryModeState_ARRAYSIZE ((telemetry_vehicle_data_SentryModeState)(telemetry_vehicle_data_SentryModeState_SentryModeStateQuiet+1))

#define _telemetry_vehicle_data_SpeedAssistLevel_MIN telemetry_vehicle_data_SpeedAssistLevel_SpeedAssistLevelUnknown
#define _telemetry_vehicle_data_SpeedAssistLevel_MAX telemetry_vehicle_data_SpeedAssistLevel_SpeedAssistLevelChime
#define _telemetry_vehicle_data_SpeedAssistLevel_ARRAYSIZE ((telemetry_vehicle_data_SpeedAssistLevel)(telemetry_vehicle_data_SpeedAssistLevel_SpeedAssistLevelChime+1))

#define _telemetry_vehicle_data_BMSStateValue_MIN telemetry_vehicle_data_BMSStateValue_BMSStateUnknown
#define _telemetry_vehicle_data_BMSStateValue_MAX telemetry_vehicle_data_BMSStateValue_BMSStateSNA
#define _telemetry_vehicle_data_BMSStateValue_ARRAYSIZE ((telemetry_vehicle_data_BMSStateValue)(telemetry_vehicle_data_BMSStateValue_BMSStateSNA+1))

#define _telemetry_vehicle_data_BuckleStatus_MIN telemetry_vehicle_data_BuckleStatus_BuckleStatusUnknown
#define _telemetry_vehicle_data_BuckleStatus_MAX telemetry_vehicle_data_BuckleStatus_BuckleStatusFaulted
#define _telemetry_vehicle_data_BuckleStatus_ARRAYSIZE ((telemetry_vehicle_data_BuckleStatus)(telemetry_vehicle_data_BuckleStatus_BuckleStatusFaulted+1))

#define _telemetry_vehicle_data_CarTypeValue_MIN telemetry_vehicle_data_CarTypeValue_CarTypeUnknown
#define _telemetry_vehicle_data_CarTypeValue_MAX telemetry_vehicle_data_CarTypeValue_CarTypeCybertruck
#define _telemetry_vehicle_data_CarTypeValue_ARRAYSIZE ((telemetry_vehicle_data_CarTypeValue)(telemetry_vehicle_data_CarTypeValue_CarTypeCybertruck+1))

#define _telemetry_vehicle_data_ChargePortValue_MIN telemetry_vehicle_data_ChargePortValue_ChargePortUnknown
#define _telemetry_vehicle_data_ChargePortValue_MAX telemetry_vehicle_data_ChargePortValue_ChargePortCCS
#define _telemetry_vehicle_data_ChargePortValue_ARRAYSIZE ((telemetry_vehicle_data_ChargePortValue)(telemetry_vehicle_data_ChargePortValue_ChargePortCCS+1))

#define _telemetry_vehicle_data_ChargePortLatchValue_MIN telemetry_vehicle_data_ChargePortLatchValue_ChargePortLatchUnknown
#define _telemetry_vehicle_data_ChargePortLatchValue_MAX telemetry_vehicle_data_ChargePortLatchValue_ChargePortLatchBlocking
#define _telemetry_vehicle_data_ChargePortLatchValue_ARRAYSIZE ((telemetry_vehicle_data_ChargePortLatchValue)(telemetry_vehicle_data_ChargePortLatchValue_ChargePortLatchBlocking+1))

#define _telemetry_vehicle_data_DriveInverterState_MIN telemetry_vehicle_data_DriveInverterState_DriveInverterStateUnknown
#define _telemetry_vehicle_data_DriveInverterState_MAX telemetry_vehicle_data_DriveInverterState_DriveInverterStateEnable
#define _telemetry_vehicle_data_DriveInverterState_ARRAYSIZE ((telemetry_vehicle_data_DriveInverterState)(telemetry_vehicle_data_DriveInverterState_DriveInverterStateEnable+1))

#define _telemetry_vehicle_data_HvilStatus_MIN telemetry_vehicle_data_HvilStatus_HvilStatusUnknown
#define _telemetry_vehicle_data_HvilStatus_MAX telemetry_vehicle_data_HvilStatus_HvilStatusOK
#define _telemetry_vehicle_data_HvilStatus_ARRAYSIZE ((telemetry_vehicle_data_HvilStatus)(telemetry_vehicle_data_HvilStatus_HvilStatusOK+1))

#define _telemetry_vehicle_data_WindowState_MIN telemetry_vehicle_data_WindowState_WindowStateUnknown
#define _telemetry_vehicle_data_WindowState_MAX telemetry_vehicle_data_WindowState_WindowStateOpened
#define _telemetry_vehicle_data_WindowState_ARRAYSIZE ((telemetry_vehicle_data_WindowState)(telemetry_vehicle_data_WindowState_WindowStateOpened+1))

#define _telemetry_vehicle_data_SeatFoldPosition_MIN telemetry_vehicle_data_SeatFoldPosition_SeatFoldPositionUnknown
#define _telemetry_vehicle_data_SeatFoldPosition_MAX telemetry_vehicle_data_SeatFoldPosition_SeatFoldPositionUnfolded
#define _telemetry_vehicle_data_SeatFoldPosition_ARRAYSIZE ((telemetry_vehicle_data_SeatFoldPosition)(telemetry_vehicle_data_SeatFoldPosition_SeatFoldPositionUnfolded+1))

#define _telemetry_vehicle_data_TractorAirStatus_MIN telemetry_vehicle_data_TractorAirStatus_TractorAirStatusUnknown
#define _telemetry_vehicle_data_TractorAirStatus_MAX telemetry_vehicle_data_TractorAirStatus_TractorAirStatusExhausted
#define _telemetry_vehicle_data_TractorAirStatus_ARRAYSIZE ((telemetry_vehicle_data_TractorAirStatus)(telemetry_vehicle_data_TractorAirStatus_TractorAirStatusExhausted+1))

#define _telemetry_vehicle_data_TrailerAirStatus_MIN telemetry_vehicle_data_TrailerAirStatus_TrailerAirStatusUnknown
#define _telemetry_vehicle_data_TrailerAirStatus_MAX telemetry_vehicle_data_TrailerAirStatus_TrailerAirStatusExhausted
#define _telemetry_vehicle_data_TrailerAirStatus_ARRAYSIZE ((telemetry_vehicle_data_TrailerAirStatus)(telemetry_vehicle_data_TrailerAirStatus_TrailerAirStatusExhausted+1))

#define _telemetry_vehicle_data_HvacAutoModeState_MIN telemetry_vehicle_data_HvacAutoModeState_HvacAutoModeStateUnknown
#define _telemetry_vehicle_data_HvacAutoModeState_MAX telemetry_vehicle_data_HvacAutoModeState_HvacAutoModeStateOverride
#define _telemetry_vehicle_data_HvacAutoModeState_ARRAYSIZE ((telemetry_vehicle_data_HvacAutoModeState)(telemetry_vehicle_data_HvacAutoModeState_HvacAutoModeStateOverride+1))

#define _telemetry_vehicle_data_CabinOverheatProtectionModeState_MIN telemetry_vehicle_data_CabinOverheatProtectionModeState_CabinOverheatProtectionModeStateUnknown
#define _telemetry_vehicle_data_CabinOverheatProtectionModeState_MAX telemetry_vehicle_data_CabinOverheatProtectionModeState_CabinOverheatProtectionModeStateFanOnly
#define _telemetry_vehicle_data_CabinOverheatProtectionModeState_ARRAYSIZE ((telemetry_vehicle_data_CabinOverheatProtectionModeState)(telemetry_vehicle_data_CabinOverheatProtectionModeState_CabinOverheatProtectionModeStateFanOnly+1))

#define _telemetry_vehicle_data_ClimateOverheatProtectionTempLimit_MIN telemetry_vehicle_data_ClimateOverheatProtectionTempLimit_ClimateOverheatProtectionTempLimitUnknown
#define _telemetry_vehicle_data_ClimateOverheatProtectionTempLimit_MAX telemetry_vehicle_data_ClimateOverheatProtectionTempLimit_ClimateOverheatProtectionTempLimitLow
#define _telemetry_vehicle_data_ClimateOverheatProtectionTempLimit_ARRAYSIZE ((telemetry_vehicle_data_ClimateOverheatProtectionTempLimit)(telemetry_vehicle_data_ClimateOverheatProtectionTempLimit_ClimateOverheatProtectionTempLimitLow+1))

#define _telemetry_vehicle_data_DefrostModeState_MIN telemetry_vehicle_data_DefrostModeState_DefrostModeStateUnknown
#define _telemetry_vehicle_data_DefrostModeState_MAX telemetry_vehicle_data_DefrostModeState_DefrostModeStateAutoDefog
#define _telemetry_vehicle_data_DefrostModeState_ARRAYSIZE ((telemetry_vehicle_data_DefrostModeState)(telemetry_vehicle_data_DefrostModeState_DefrostModeStateAutoDefog+1))

#define _telemetry_vehicle_data_ClimateKeeperModeState_MIN telemetry_vehicle_data_ClimateKeeperModeState_ClimateKeeperModeStateUnknown
#define _telemetry_vehicle_data_ClimateKeeperModeState_MAX telemetry_vehicle_data_ClimateKeeperModeState_ClimateKeeperModeStateParty
#define _telemetry_vehicle_data_ClimateKeeperModeState_ARRAYSIZE ((telemetry_vehicle_data_ClimateKeeperModeState)(telemetry_vehicle_data_ClimateKeeperModeState_ClimateKeeperModeStateParty+1))

#define _telemetry_vehicle_data_HvacPowerState_MIN telemetry_vehicle_data_HvacPowerState_HvacPowerStateUnknown
#define _telemetry_vehicle_data_HvacPowerState_MAX telemetry_vehicle_data_HvacPowerState_HvacPowerStateOverheatProtect
#define _telemetry_vehicle_data_HvacPowerState_ARRAYSIZE ((telemetry_vehicle_data_HvacPowerState)(telemetry_vehicle_data_HvacPowerState_HvacPowerStateOverheatProtect+1))

#define _telemetry_vehicle_data_FastCharger_MIN telemetry_vehicle_data_FastCharger_FastChargerUnknown
#define _telemetry_vehicle_data_FastCharger_MAX telemetry_vehicle_data_FastCharger_FastChargerSNA
#define _telemetry_vehicle_data_FastCharger_ARRAYSIZE ((telemetry_vehicle_data_FastCharger)(telemetry_vehicle_data_FastCharger_FastChargerSNA+1))

#define _telemetry_vehicle_data_CableType_MIN telemetry_vehicle_data_CableType_CableTypeUnknown
#define _telemetry_vehicle_data_CableType_MAX telemetry_vehicle_data_CableType_CableTypeSNA
#define _telemetry_vehicle_data_CableType_ARRAYSIZE ((telemetry_vehicle_data_CableType)(telemetry_vehicle_data_CableType_CableTypeSNA+1))

#define _telemetry_vehicle_data_TonneauTentModeState_MIN telemetry_vehicle_data_TonneauTentModeState_TonneauTentModeStateUnknown
#define _telemetry_vehicle_data_TonneauTentModeState_MAX telemetry_vehicle_data_TonneauTentModeState_TonneauTentModeStateActive
#define _telemetry_vehicle_data_TonneauTentModeState_ARRAYSIZE ((telemetry_vehicle_data_TonneauTentModeState)(telemetry_vehicle_data_TonneauTentModeState_TonneauTentModeStateActive+1))

#define _telemetry_vehicle_data_TonneauPositionState_MIN telemetry_vehicle_data_TonneauPositionState_TonneauPositionStateUnknown
#define _telemetry_vehicle_data_TonneauPositionState_MAX telemetry_vehicle_data_TonneauPositionState_TonneauPositionStateFullyOpen
#define _telemetry_vehicle_data_TonneauPositionState_ARRAYSIZE ((telemetry_vehicle_data_TonneauPositionState)(telemetry_vehicle_data_TonneauPositionState_TonneauPositionStateFullyOpen+1))

#define _telemetry_vehicle_data_PowershareState_MIN telemetry_vehicle_data_PowershareState_PowershareStateUnknown
#define _telemetry_vehicle_data_PowershareState_MAX telemetry_vehicle_data_PowershareState_PowershareStateStopped
#define _telemetry_vehicle_data_PowershareState_ARRAYSIZE ((telemetry_vehicle_data_PowershareState)(telemetry_vehicle_data_PowershareState_PowershareStateStopped+1))

#define _telemetry_vehicle_data_PowershareStopReasonStatus_MIN telemetry_vehicle_data_PowershareStopReasonStatus_PowershareStopReasonStatusUnknown
#define _telemetry_vehicle_data_PowershareStopReasonStatus_MAX telemetry_vehicle_data_PowershareStopReasonStatus_PowershareStopReasonStatusAuthentication
#define _telemetry_vehicle_data_PowershareStopReasonStatus_ARRAYSIZE ((telemetry_vehicle_data_PowershareStopReasonStatus)(telemetry_vehicle_data_PowershareStopReasonStatus_PowershareStopReasonStatusAuthentication+1))

#define _telemetry_vehicle_data_PowershareTypeStatus_MIN telemetry_vehicle_data_PowershareTypeStatus_PowershareTypeStatusUnknown
#define _telemetry_vehicle_data_PowershareTypeStatus_MAX telemetry_vehicle_data_PowershareTypeStatus_PowershareTypeStatusHome
#define _telemetry_vehicle_data_PowershareTypeStatus_ARRAYSIZE ((telemetry_vehicle_data_PowershareTypeStatus)(telemetry_vehicle_data_PowershareTypeStatus_PowershareTypeStatusHome+1))

#define _telemetry_vehicle_data_DisplayState_MIN telemetry_vehicle_data_DisplayState_DisplayStateUnknown
#define _telemetry_vehicle_data_DisplayState_MAX telemetry_vehicle_data_DisplayState_DisplayStateEntertainment
#define _telemetry_vehicle_data_DisplayState_ARRAYSIZE ((telemetry_vehicle_data_DisplayState)(telemetry_vehicle_data_DisplayState_DisplayStateEntertainment+1))

#define _telemetry_vehicle_data_DistanceUnit_MIN telemetry_vehicle_data_DistanceUnit_DistanceUnitUnknown
#define _telemetry_vehicle_data_DistanceUnit_MAX telemetry_vehicle_data_DistanceUnit_DistanceUnitKilometers
#define _telemetry_vehicle_data_DistanceUnit_ARRAYSIZE ((telemetry_vehicle_data_DistanceUnit)(telemetry_vehicle_data_DistanceUnit_DistanceUnitKilometers+1))

#define _telemetry_vehicle_data_TemperatureUnit_MIN telemetry_vehicle_data_TemperatureUnit_TemperatureUnitUnknown
#define _telemetry_vehicle_data_TemperatureUnit_MAX telemetry_vehicle_data_TemperatureUnit_TemperatureUnitCelsius
#define _telemetry_vehicle_data_TemperatureUnit_ARRAYSIZE ((telemetry_vehicle_data_TemperatureUnit)(telemetry_vehicle_data_TemperatureUnit_TemperatureUnitCelsius+1))

#define _telemetry_vehicle_data_PressureUnit_MIN telemetry_vehicle_data_PressureUnit_PressureUnitUnknown
#define _telemetry_vehicle_data_PressureUnit_MAX telemetry_vehicle_data_PressureUnit_PressureUnitBar
#define _telemetry_vehicle_data_PressureUnit_ARRAYSIZE ((telemetry_vehicle_data_PressureUnit)(telemetry_vehicle_data_PressureUnit_PressureUnitBar+1))

#define _telemetry_vehicle_data_ChargeUnitPreference_MIN telemetry_vehicle_data_ChargeUnitPreference_ChargeUnitUnknown
#define _telemetry_vehicle_data_ChargeUnitPreference_MAX telemetry_vehicle_data_ChargeUnitPreference_ChargeUnitPercent
#define _telemetry_vehicle_data_ChargeUnitPreference_ARRAYSIZE ((telemetry_vehicle_data_ChargeUnitPreference)(telemetry_vehicle_data_ChargeUnitPreference_ChargeUnitPercent+1))

#define _telemetry_vehicle_data_SunroofInstalledState_MIN telemetry_vehicle_data_SunroofInstalledState_SunroofInstalledStateUnknown
#define _telemetry_vehicle_data_SunroofInstalledState_MAX telemetry_vehicle_data_SunroofInstalledState_SunroofInstalledStateGen2Installed
#define _telemetry_vehicle_data_SunroofInstalledState_ARRAYSIZE ((telemetry_vehicle_data_SunroofInstalledState)(telemetry_vehicle_data_SunroofInstalledState_SunroofInstalledStateGen2Installed+1))

#define _telemetry_vehicle_data_TurnSignalState_MIN telemetry_vehicle_data_TurnSignalState_TurnSignalStateUnknown
#define _telemetry_vehicle_data_TurnSignalState_MAX telemetry_vehicle_data_TurnSignalState_TurnSignalStateBoth
#define _telemetry_vehicle_data_TurnSignalState_ARRAYSIZE ((telemetry_vehicle_data_TurnSignalState)(telemetry_vehicle_data_TurnSignalState_TurnSignalStateBoth+1))

#define _telemetry_vehicle_data_MediaStatus_MIN telemetry_vehicle_data_MediaStatus_MediaStatusUnknown
#define _telemetry_vehicle_data_MediaStatus_MAX telemetry_vehicle_data_MediaStatus_MediaStatusPaused
#define _telemetry_vehicle_data_MediaStatus_ARRAYSIZE ((telemetry_vehicle_data_MediaStatus)(telemetry_vehicle_data_MediaStatus_MediaStatusPaused+1))





#define telemetry_vehicle_data_Value_value_charging_value_ENUMTYPE telemetry_vehicle_data_ChargingState
#define telemetry_vehicle_data_Value_value_shift_state_value_ENUMTYPE telemetry_vehicle_data_ShiftState
#define telemetry_vehicle_data_Value_value_lane_assist_level_value_ENUMTYPE telemetry_vehicle_data_LaneAssistLevel
#define telemetry_vehicle_data_Value_value_scheduled_charging_mode_value_ENUMTYPE telemetry_vehicle_data_ScheduledChargingModeValue
#define telemetry_vehicle_data_Value_value_sentry_mode_state_value_ENUMTYPE telemetry_vehicle_data_SentryModeState
#define telemetry_vehicle_data_Value_value_speed_assist_level_value_ENUMTYPE telemetry_vehicle_data_SpeedAssistLevel
#define telemetry_vehicle_data_Value_value_bms_state_value_ENUMTYPE telemetry_vehicle_data_BMSStateValue
#define telemetry_vehicle_data_Value_value_buckle_status_value_ENUMTYPE telemetry_vehicle_data_BuckleStatus
#define telemetry_vehicle_data_Value_value_car_type_value_ENUMTYPE telemetry_vehicle_data_CarTypeValue
#define telemetry_vehicle_data_Value_value_charge_port_value_ENUMTYPE telemetry_vehicle_data_ChargePortValue
#define telemetry_vehicle_data_Value_value_charge_port_latch_value_ENUMTYPE telemetry_vehicle_data_ChargePortLatchValue
#define telemetry_vehicle_data_Value_value_drive_inverter_state_value_ENUMTYPE telemetry_vehicle_data_DriveInverterState
#define telemetry_vehicle_data_Value_value_hvil_status_value_ENUMTYPE telemetry_vehicle_data_HvilStatus
#define telemetry_vehicle_data_Value_value_window_state_value_ENUMTYPE telemetry_vehicle_data_WindowState
#define telemetry_vehicle_data_Value_value_seat_fold_position_value_ENUMTYPE telemetry_vehicle_data_SeatFoldPosition
#define telemetry_vehicle_data_Value_value_tractor_air_status_value_ENUMTYPE telemetry_vehicle_data_TractorAirStatus
#define telemetry_vehicle_data_Value_value_follow_distance_value_ENUMTYPE telemetry_vehicle_data_FollowDistance
#define telemetry_vehicle_data_Value_value_forward_collision_sensitivity_value_ENUMTYPE telemetry_vehicle_data_ForwardCollisionSensitivity
#define telemetry_vehicle_data_Value_value_guest_mode_mobile_access_value_ENUMTYPE telemetry_vehicle_data_GuestModeMobileAccess
#define telemetry_vehicle_data_Value_value_trailer_air_status_value_ENUMTYPE telemetry_vehicle_data_TrailerAirStatus
#define telemetry_vehicle_data_Value_value_detailed_charge_state_value_ENUMTYPE telemetry_vehicle_data_DetailedChargeStateValue
#define telemetry_vehicle_data_Value_value_hvac_auto_mode_value_ENUMTYPE telemetry_vehicle_data_HvacAutoModeState
#define telemetry_vehicle_data_Value_value_cabin_overheat_protection_mode_value_ENUMTYPE telemetry_vehicle_data_CabinOverheatProtectionModeState
#define telemetry_vehicle_data_Value_value_cabin_overheat_protection_temperature_limit_value_ENUMTYPE telemetry_vehicle_data_ClimateOverheatProtectionTempLimit
#define telemetry_vehicle_data_Value_value_defrost_mode_value_ENUMTYPE telemetry_vehicle_data_DefrostModeState
#define telemetry_vehicle_data_Value_value_climate_keeper_mode_value_ENUMTYPE telemetry_vehicle_data_ClimateKeeperModeState
#define telemetry_vehicle_data_Value_value_hvac_power_value_ENUMTYPE telemetry_vehicle_data_HvacPowerState
#define telemetry_vehicle_data_Value_value_fast_charger_value_ENUMTYPE telemetry_vehicle_data_FastCharger
#define telemetry_vehicle_data_Value_value_cable_type_value_ENUMTYPE telemetry_vehicle_data_CableType
#define telemetry_vehicle_data_Value_value_tonneau_tent_mode_value_ENUMTYPE telemetry_vehicle_data_TonneauTentModeState
#define telemetry_vehicle_data_Value_value_tonneau_position_value_ENUMTYPE telemetry_vehicle_data_TonneauPositionState
#define telemetry_vehicle_data_Value_value_powershare_type_value_ENUMTYPE telemetry_vehicle_data_PowershareTypeStatus
#define telemetry_vehicle_data_Value_value_powershare_state_value_ENUMTYPE telemetry_vehicle_data_PowershareState
#define telemetry_vehicle_data_Value_value_powershare_stop_reason_value_ENUMTYPE telemetry_vehicle_data_PowershareStopReasonStatus
#define telemetry_vehicle_data_Value_value_display_state_value_ENUMTYPE telemetry_vehicle_data_DisplayState
#define telemetry_vehicle_data_Value_value_distance_unit_value_ENUMTYPE telemetry_vehicle_data_DistanceUnit
#define telemetry_vehicle_data_Value_value_temperature_unit_value_ENUMTYPE telemetry_vehicle_data_TemperatureUnit
#define telemetry_vehicle_data_Value_value_pressure_unit_value_ENUMTYPE telemetry_vehicle_data_PressureUnit
#define telemetry_vehicle_data_Value_value_charge_unit_preference_value_ENUMTYPE telemetry_vehicle_data_ChargeUnitPreference
#define telemetry_vehicle_data_Value_value_turn_signal_state_value_ENUMTYPE telemetry_vehicle_data_TurnSignalState
#define telemetry_vehicle_data_Value_value_media_status_value_ENUMTYPE telemetry_vehicle_data_MediaStatus
#define telemetry_vehicle_data_Value_value_sunroof_installed_state_value_ENUMTYPE telemetry_vehicle_data_SunroofInstalledState

#define telemetry_vehicle_data_Datum_key_ENUMTYPE telemetry_vehicle_data_Field



/* Initializer values for message structs */
#define telemetry_vehicle_data_LocationValue_init_default {0, 0}
#define telemetry_vehicle_data_Doors_init_default {0, 0, 0, 0, 0, 0}
#define telemetry_vehicle_data_TireLocation_init_default {0, 0, 0, 0, 0, 0, 0, 0, 0, 0}
#define telemetry_vehicle_data_Time_init_default {0, 0, 0}
#define telemetry_vehicle_data_Value_init_default {0, {{{NULL}, NULL}}}
#define telemetry_vehicle_data_Datum_init_default {_telemetry_vehicle_data_Field_MIN, false, telemetry_vehicle_data_Value_init_default}
#define telemetry_vehicle_data_Payload_init_default {{{NULL}, NULL}, {{NULL}, NULL}, 0}
#define telemetry_vehicle_data_LocationValue_init_zero {0, 0}
#define telemetry_vehicle_data_Doors_init_zero   {0, 0, 0, 0, 0, 0}
#define telemetry_vehicle_data_TireLocation_init_zero {0, 0, 0, 0, 0, 0, 0, 0, 0, 0}
#define telemetry_vehicle_data_Time_init_zero    {0, 0, 0}
#define telemetry_vehicle_data_Value_init_zero   {0, {{{NULL}, NULL}}}
#define telemetry_vehicle_data_Datum_init_zero   {_telemetry_vehicle_data_Field_MIN, false, telemetry_vehicle_data_Value_init_zero}
#define telemetry_vehicle_data_Payload_init_zero {{{NULL}, NULL}, {{NULL}, NULL}, 0}

/* Field tags (for use in manual encoding/decoding) */
#define telemetry_vehicle_data_LocationValue_latitude_tag 1
#define telemetry_vehicle_data_LocationValue_longitude_tag 2
#define telemetry_vehicle_data_Doors_DriverFront_tag 1
#define telemetry_vehicle_data_Doors_DriverRear_tag 2
#define telemetry_vehicle_data_Doors_PassengerFront_tag 3
#define telemetry_vehicle_data_Doors_PassengerRear_tag 4
#define telemetry_vehicle_data_Doors_TrunkFront_tag 5
#define telemetry_vehicle_data_Doors_TrunkRear_tag 6
#define telemetry_vehicle_data_TireLocation_front_left_tag 1
#define telemetry_vehicle_data_TireLocation_front_right_tag 2
#define telemetry_vehicle_data_TireLocation_rear_left_tag 3
#define telemetry_vehicle_data_TireLocation_rear_right_tag 4
#define telemetry_vehicle_data_TireLocation_semi_middle_axle_left_2_tag 5
#define telemetry_vehicle_data_TireLocation_semi_middle_axle_right_2_tag 6
#define telemetry_vehicle_data_TireLocation_semi_rear_axle_left_tag 7
#define telemetry_vehicle_data_TireLocation_semi_rear_axle_right_tag 8
#define telemetry_vehicle_data_TireLocation_semi_rear_axle_left_2_tag 9
#define telemetry_vehicle_data_TireLocation_semi_rear_axle_right_2_tag 10
#define telemetry_vehicle_data_Time_hour_tag     1
#define telemetry_vehicle_data_Time_minute_tag   2
#define telemetry_vehicle_data_Time_second_tag   3
#define telemetry_vehicle_data_Value_string_value_tag 1
#define telemetry_vehicle_data_Value_int_value_tag 2
#define telemetry_vehicle_data_Value_long_value_tag 3
#define telemetry_vehicle_data_Value_float_value_tag 4
#define telemetry_vehicle_data_Value_double_value_tag 5
#define telemetry_vehicle_data_Value_boolean_value_tag 6
#define telemetry_vehicle_data_Value_location_value_tag 7
#define telemetry_vehicle_data_Value_charging_value_tag 8
#define telemetry_vehicle_data_Value_shift_state_value_tag 9
#define telemetry_vehicle_data_Value_invalid_tag 10
#define telemetry_vehicle_data_Value_lane_assist_level_value_tag 11
#define telemetry_vehicle_data_Value_scheduled_charging_mode_value_tag 12
#define telemetry_vehicle_data_Value_sentry_mode_state_value_tag 13
#define telemetry_vehicle_data_Value_speed_assist_level_value_tag 14
#define telemetry_vehicle_data_Value_bms_state_value_tag 15
#define telemetry_vehicle_data_Value_buckle_status_value_tag 16
#define telemetry_vehicle_data_Value_car_type_value_tag 17
#define telemetry_vehicle_data_Value_charge_port_value_tag 18
#define telemetry_vehicle_data_Value_charge_port_latch_value_tag 19
#define telemetry_vehicle_data_Value_door_value_tag 21
#define telemetry_vehicle_data_Value_drive_inverter_state_value_tag 22
#define telemetry_vehicle_data_Value_hvil_status_value_tag 23
#define telemetry_vehicle_data_Value_window_state_value_tag 24
#define telemetry_vehicle_data_Value_seat_fold_position_value_tag 25
#define telemetry_vehicle_data_Value_tractor_air_status_value_tag 26
#define telemetry_vehicle_data_Value_follow_distance_value_tag 27
#define telemetry_vehicle_data_Value_forward_collision_sensitivity_value_tag 28
#define telemetry_vehicle_data_Value_guest_mode_mobile_access_value_tag 29
#define telemetry_vehicle_data_Value_trailer_air_status_value_tag 30
#define telemetry_vehicle_data_Value_time_value_tag 31
#define telemetry_vehicle_data_Value_detailed_charge_state_value_tag 32
#define telemetry_vehicle_data_Value_hvac_auto_mode_value_tag 33
#define telemetry_vehicle_data_Value_cabin_overheat_protection_mode_value_tag 34
#define telemetry_vehicle_data_Value_cabin_overheat_protection_temperature_limit_value_tag 35
#define telemetry_vehicle_data_Value_defrost_mode_value_tag 36
#define telemetry_vehicle_data_Value_climate_keeper_mode_value_tag 37
#define telemetry_vehicle_data_Value_hvac_power_value_tag 38
#define telemetry_vehicle_data_Value_tire_location_value_tag 39
#define telemetry_vehicle_data_Value_fast_charger_value_tag 40
#define telemetry_vehicle_data_Value_cable_type_value_tag 41
#define telemetry_vehicle_data_Value_tonneau_tent_mode_value_tag 42
#define telemetry_vehicle_data_Value_tonneau_position_value_tag 43
#define telemetry_vehicle_data_Value_powershare_type_value_tag 44
#define telemetry_vehicle_data_Value_powershare_state_value_tag 45
#define telemetry_vehicle_data_Value_powershare_stop_reason_value_tag 46
#define telemetry_vehicle_data_Value_display_state_value_tag 47
#define telemetry_vehicle_data_Value_distance_unit_value_tag 48
#define telemetry_vehicle_data_Value_temperature_unit_value_tag 49
#define telemetry_vehicle_data_Value_pressure_unit_value_tag 50
#define telemetry_vehicle_data_Value_charge_unit_preference_value_tag 51
#define telemetry_vehicle_data_Value_turn_signal_state_value_tag 52
#define telemetry_vehicle_data_Value_media_status_value_tag 53
#define telemetry_vehicle_data_Value_sunroof_installed_state_value_tag 54
#define telemetry_vehicle_data_Datum_key_tag     1
#define telemetry_vehicle_data_Datum_value_tag   2
#define telemetry_vehicle_data_Payload_data_tag  1
#define telemetry_vehicle_data_Payload_vin_tag   3
#define telemetry_vehicle_data_Payload_is_resend_tag 4

/* Struct field encoding specification for nanopb */
#define telemetry_vehicle_data_LocationValue_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, DOUBLE,   latitude,          1) \
X(a, STATIC,   SINGULAR, DOUBLE,   longitude,         2)
#define telemetry_vehicle_data_LocationValue_CALLBACK NULL
#define telemetry_vehicle_data_LocationValue_DEFAULT NULL

#define telemetry_vehicle_data_Doors_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, BOOL,     DriverFront,       1) \
X(a, STATIC,   SINGULAR, BOOL,     DriverRear,        2) \
X(a, STATIC,   SINGULAR, BOOL,     PassengerFront,    3) \
X(a, STATIC,   SINGULAR, BOOL,     PassengerRear,     4) \
X(a, STATIC,   SINGULAR, BOOL,     TrunkFront,        5) \
X(a, STATIC,   SINGULAR, BOOL,     TrunkRear,         6)
#define telemetry_vehicle_data_Doors_CALLBACK NULL
#define telemetry_vehicle_data_Doors_DEFAULT NULL

#define telemetry_vehicle_data_TireLocation_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, BOOL,     front_left,        1) \
X(a, STATIC,   SINGULAR, BOOL,     front_right,       2) \
X(a, STATIC,   SINGULAR, BOOL,     rear_left,         3) \
X(a, STATIC,   SINGULAR, BOOL,     rear_right,        4) \
X(a, STATIC,   SINGULAR, BOOL,     semi_middle_axle_left_2,   5) \
X(a, STATIC,   SINGULAR, BOOL,     semi_middle_axle_right_2,   6) \
X(a, STATIC,   SINGULAR, BOOL,     semi_rear_axle_left,   7) \
X(a, STATIC,   SINGULAR, BOOL,     semi_rear_axle_right,   8) \
X(a, STATIC,   SINGULAR, BOOL,     semi_rear_axle_left_2,   9) \
X(a, STATIC,   SINGULAR, BOOL,     semi_rear_axle_right_2,  10)
#define telemetry_vehicle_data_TireLocation_CALLBACK NULL
#define telemetry_vehicle_data_TireLocation_DEFAULT NULL

#define telemetry_vehicle_data_Time_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, INT32,    hour,              1) \
X(a, STATIC,   SINGULAR, INT32,    minute,            2) \
X(a, STATIC,   SINGULAR, INT32,    second,            3)
#define telemetry_vehicle_data_Time_CALLBACK NULL
#define telemetry_vehicle_data_Time_DEFAULT NULL

#define telemetry_vehicle_data_Value_FIELDLIST(X, a) \
X(a, CALLBACK, ONEOF,    STRING,   (value,string_value,value.string_value),   1) \
X(a, STATIC,   ONEOF,    INT32,    (value,int_value,value.int_value),   2) \
X(a, STATIC,   ONEOF,    INT64,    (value,long_value,value.long_value),   3) \
X(a, STATIC,   ONEOF,    FLOAT,    (value,float_value,value.float_value),   4) \
X(a, STATIC,   ONEOF,    DOUBLE,   (value,double_value,value.double_value),   5) \
X(a, STATIC,   ONEOF,    BOOL,     (value,boolean_value,value.boolean_value),   6) \
X(a, STATIC,   ONEOF,    MESSAGE,  (value,location_value,value.location_value),   7) \
X(a, STATIC,   ONEOF,    UENUM,    (value,charging_value,value.charging_value),   8) \
X(a, STATIC,   ONEOF,    UENUM,    (value,shift_state_value,value.shift_state_value),   9) \
X(a, STATIC,   ONEOF,    BOOL,     (value,invalid,value.invalid),  10) \
X(a, STATIC,   ONEOF,    UENUM,    (value,lane_assist_level_value,value.lane_assist_level_value),  11) \
X(a, STATIC,   ONEOF,    UENUM,    (value,scheduled_charging_mode_value,value.scheduled_charging_mode_value),  12) \
X(a, STATIC,   ONEOF,    UENUM,    (value,sentry_mode_state_value,value.sentry_mode_state_value),  13) \
X(a, STATIC,   ONEOF,    UENUM,    (value,speed_assist_level_value,value.speed_assist_level_value),  14) \
X(a, STATIC,   ONEOF,    UENUM,    (value,bms_state_value,value.bms_state_value),  15) \
X(a, STATIC,   ONEOF,    UENUM,    (value,buckle_status_value,value.buckle_status_value),  16) \
X(a, STATIC,   ONEOF,    UENUM,    (value,car_type_value,value.car_type_value),  17) \
X(a, STATIC,   ONEOF,    UENUM,    (value,charge_port_value,value.charge_port_value),  18) \
X(a, STATIC,   ONEOF,    UENUM,    (value,charge_port_latch_value,value.charge_port_latch_value),  19) \
X(a, STATIC,   ONEOF,    MESSAGE,  (value,door_value,value.door_value),  21) \
X(a, STATIC,   ONEOF,    UENUM,    (value,drive_inverter_state_value,value.drive_inverter_state_value),  22) \
X(a, STATIC,   ONEOF,    UENUM,    (value,hvil_status_value,value.hvil_status_value),  23) \
X(a, STATIC,   ONEOF,    UENUM,    (value,window_state_value,value.window_state_value),  24) \
X(a, STATIC,   ONEOF,    UENUM,    (value,seat_fold_position_value,value.seat_fold_position_value),  25) \
X(a, STATIC,   ONEOF,    UENUM,    (value,tractor_air_status_value,value.tractor_air_status_value),  26) \
X(a, STATIC,   ONEOF,    UENUM,    (value,follow_distance_value,value.follow_distance_value),  27) \
X(a, STATIC,   ONEOF,    UENUM,    (value,forward_collision_sensitivity_value,value.forward_collision_sensitivity_value),  28) \
X(a, STATIC,   ONEOF,    UENUM,    (value,guest_mode_mobile_access_value,value.guest_mode_mobile_access_value),  29) \
X(a, STATIC,   ONEOF,    UENUM,    (value,trailer_air_status_value,value.trailer_air_status_value),  30) \
X(a, STATIC,   ONEOF,    MESSAGE,  (value,time_value,value.time_value),  31) \
X(a, STATIC,   ONEOF,    UENUM,    (value,detailed_charge_state_value,value.detailed_charge_state_value),  32) \
X(a, STATIC,   ONEOF,    UENUM,    (value,hvac_auto_mode_value,value.hvac_auto_mode_value),  33) \
X(a, STATIC,   ONEOF,    UENUM,    (value,cabin_overheat_protection_mode_value,value.cabin_overheat_protection_mode_value),  34) \
X(a, STATIC,   ONEOF,    UENUM,    (value,cabin_overheat_protection_temperature_limit_value,value.cabin_overheat_protection_temperature_limit_value),  35) \
X(a, STATIC,   ONEOF,    UENUM,    (value,defrost_mode_value,value.defrost_mode_value),  36) \
X(a, STATIC,   ONEOF,    UENUM,    (value,climate_keeper_mode_value,value.climate_keeper_mode_value),  37) \
X(a, STATIC,   ONEOF,    UENUM,    (value,hvac_power_value,value.hvac_power_value),  38) \
X(a, STATIC,   ONEOF,    MESSAGE,  (value,tire_location_value,value.tire_location_value),  39) \
X(a, STATIC,   ONEOF,    UENUM,    (value,fast_charger_value,value.fast_charger_value),  40) \
X(a, STATIC,   ONEOF,    UENUM,    (value,cable_type_value,value.cable_type_value),  41) \
X(a, STATIC,   ONEOF,    UENUM,    (value,tonneau_tent_mode_value,value.tonneau_tent_mode_value),  42) \
X(a, STATIC,   ONEOF,    UENUM,    (value,tonneau_position_value,value.tonneau_position_value),  43) \
X(a, STATIC,   ONEOF,    UENUM,    (value,powershare_type_value,value.powershare_type_value),  44) \
X(a, STATIC,   ONEOF,    UENUM,    (value,powershare_state_value,value.powershare_state_value),  45) \
X(a, STATIC,   ONEOF,    UENUM,    (value,powershare_stop_reason_value,value.powershare_stop_reason_value),  46) \
X(a, STATIC,   ONEOF,    UENUM,    (value,display_state_value,value.display_state_value),  47) \
X(a, STATIC,   ONEOF,    UENUM,    (value,distance_unit_value,value.distance_unit_value),  48) \
X(a, STATIC,   ONEOF,    UENUM,    (value,temperature_unit_value,value.temperature_unit_value),  49) \
X(a, STATIC,   ONEOF,    UENUM,    (value,pressure_unit_value,value.pressure_unit_value),  50) \
X(a, STATIC,   ONEOF,    UENUM,    (value,charge_unit_preference_value,value.charge_unit_preference_value),  51) \
X(a, STATIC,   ONEOF,    UENUM,    (value,turn_signal_state_value,value.turn_signal_state_value),  52) \
X(a, STATIC,   ONEOF,    UENUM,    (value,media_status_value,value.media_status_value),  53) \
X(a, STATIC,   ONEOF,    UENUM,    (value,sunroof_installed_state_value,value.sunroof_installed_state_value),  54)
#define telemetry_vehicle_data_Value_CALLBACK pb_default_field_callback
#define telemetry_vehicle_data_Value_DEFAULT NULL
#define telemetry_vehicle_data_Value_value_location_value_MSGTYPE telemetry_vehicle_data_LocationValue
#define telemetry_vehicle_data_Value_value_door_value_MSGTYPE telemetry_vehicle_data_Doors
#define telemetry_vehicle_data_Value_value_time_value_MSGTYPE telemetry_vehicle_data_Time
#define telemetry_vehicle_data_Value_value_tire_location_value_MSGTYPE telemetry_vehicle_data_TireLocation

#define telemetry_vehicle_data_Datum_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    key,               1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  value,             2)
#define telemetry_vehicle_data_Datum_CALLBACK NULL
#define telemetry_vehicle_data_Datum_DEFAULT NULL
#define telemetry_vehicle_data_Datum_value_MSGTYPE telemetry_vehicle_data_Value

#define telemetry_vehicle_data_Payload_FIELDLIST(X, a) \
X(a, CALLBACK, REPEATED, MESSAGE,  data,              1) \
X(a, CALLBACK, SINGULAR, STRING,   vin,               3) \
X(a, STATIC,   SINGULAR, BOOL,     is_resend,         4)
#define telemetry_vehicle_data_Payload_CALLBACK pb_default_field_callback
#define telemetry_vehicle_data_Payload_DEFAULT NULL
#define telemetry_vehicle_data_Payload_data_MSGTYPE telemetry_vehicle_data_Datum

extern const pb_msgdesc_t telemetry_vehicle_data_LocationValue_msg;
extern const pb_msgdesc_t telemetry_vehicle_data_Doors_msg;
extern const pb_msgdesc_t telemetry_vehicle_data_TireLocation_msg;
extern const pb_msgdesc_t telemetry_vehicle_data_Time_msg;
extern const pb_msgdesc_t telemetry_vehicle_data_Value_msg;
extern const pb_msgdesc_t telemetry_vehicle_data_Datum_msg;
extern const pb_msgdesc_t telemetry_vehicle_data_Payload_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define telemetry_vehicle_data_LocationValue_fields &telemetry_vehicle_data_LocationValue_msg
#define telemetry_vehicle_data_Doors_fields &telemetry_vehicle_data_Doors_msg
#define telemetry_vehicle_data_TireLocation_fields &telemetry_vehicle_data_TireLocation_msg
#define telemetry_vehicle_data_Time_fields &telemetry_vehicle_data_Time_msg
#define telemetry_vehicle_data_Value_fields &telemetry_vehicle_data_Value_msg
#define telemetry_vehicle_data_Datum_fields &telemetry_vehicle_data_Datum_msg
#define telemetry_vehicle_data_Payload_fields &telemetry_vehicle_data_Payload_msg

/* Maximum encoded size of messages (where known) */
/* telemetry_vehicle_data_Value_size depends on runtime parameters */
/* telemetry_vehicle_data_Datum_size depends on runtime parameters */
/* telemetry_vehicle_data_Payload_size depends on runtime parameters */
#define TELEMETRY_VEHICLE_DATA_VEHICLE_MIN_PB_H_MAX_SIZE telemetry_vehicle_data_Time_size
#define telemetry_vehicle_data_Doors_size        12
#define telemetry_vehicle_data_LocationValue_size 18
#define telemetry_vehicle_data_Time_size         33
#define telemetry_vehicle_data_TireLocation_size 20

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
