/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.9.1 */

#include "vehicle_min.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(telemetry_vehicle_data_LocationValue, telemetry_vehicle_data_LocationValue, AUTO)


PB_BIND(telemetry_vehicle_data_Doors, telemetry_vehicle_data_Doors, AUTO)


PB_BIND(telemetry_vehicle_data_TireLocation, telemetry_vehicle_data_TireLocation, AUTO)


PB_BIND(telemetry_vehicle_data_Time, telemetry_vehicle_data_Time, AUTO)


PB_BIND(telemetry_vehicle_data_Value, telemetry_vehicle_data_Value, AUTO)


PB_BIND(telemetry_vehicle_data_Datum, telemetry_vehicle_data_Datum, AUTO)


PB_BIND(telemetry_vehicle_data_Payload, telemetry_vehicle_data_Payload, AUTO)

























































































#ifndef PB_CONVERT_DOUBLE_FLOAT
/* On some platforms (such as AVR), double is really float.
 * To be able to encode/decode double on these platforms, you need.
 * to define PB_CONVERT_DOUBLE_FLOAT in pb.h or compiler command line.
 */
PB_STATIC_ASSERT(sizeof(double) == 8, DOUBLE_MUST_BE_8_BYTES)
#endif

